(database :ldap
          (default-host "127.0.0.1")
          (default-port "389")
          (default-dn "cn=admin,Mds-Vo-name=local,o=grid")
          (default-password "alamakota"))

(object-class :top "top"
              (must :objectClass "objectClass"))

(object-class :extensibleObject "extensibleObject"
              (superclass :top))

(object-class :alias "alias"
              (superclass :top)
              (structural)
              (must :aliasedObjectName "aliasedObjectName"))

(object-class :referral "referral"
              (superclass :top)
              (structural)
              (must :ref "ref"))

(object-class :OpenLDAProotDSE "OpenLDAProotDSE"
              (superclass :top)
              (structural)
              (may :cn "cn"))

(object-class :subentry "subentry"
              (superclass :top)
              (structural)
              (must :cn "cn"))

(object-class :subschema "subschema"
              (may :objectClasses "objectClasses")
              (may :attributeTypes "attributeTypes")
              (may :matchingRules "matchingRules")
              (may :matchingRuleUse "matchingRuleUse"))

(object-class :dynamicObject "dynamicObject"
              (superclass :top))

(object-class :olcConfig "olcConfig"
              (superclass :top))

(object-class :olcGlobal "olcGlobal"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcConfigFile "olcConfigFile")
              (may :olcConfigDir "olcConfigDir")
              (may :olcAllows "olcAllows")
              (may :olcArgsFile "olcArgsFile")
              (may :olcAttributeOptions "olcAttributeOptions")
              (may :olcAuthIDRewrite "olcAuthIDRewrite")
              (may :olcAuthzPolicy "olcAuthzPolicy")
              (may :olcAuthzRegexp "olcAuthzRegexp")
              (may :olcConcurrency "olcConcurrency")
              (may :olcConnMaxPending "olcConnMaxPending")
              (may :olcConnMaxPendingAuth "olcConnMaxPendingAuth")
              (may :olcDisallows "olcDisallows")
              (may :olcGentleHUP "olcGentleHUP")
              (may :olcIdleTimeout "olcIdleTimeout")
              (may :olcIndexSubstrIfMaxLen "olcIndexSubstrIfMaxLen")
              (may :olcIndexSubstrIfMinLen "olcIndexSubstrIfMinLen")
              (may :olcIndexSubstrAnyLen "olcIndexSubstrAnyLen")
              (may :olcIndexSubstrAnyStep "olcIndexSubstrAnyStep")
              (may :olcIndexIntLen "olcIndexIntLen")
              (may :olcLocalSSF "olcLocalSSF")
              (may :olcLogFile "olcLogFile")
              (may :olcLogLevel "olcLogLevel")
              (may :olcPasswordCryptSaltFormat "olcPasswordCryptSaltFormat")
              (may :olcPasswordHash "olcPasswordHash")
              (may :olcPidFile "olcPidFile")
              (may :olcPluginLogFile "olcPluginLogFile")
              (may :olcReadOnly "olcReadOnly")
              (may :olcReferral "olcReferral")
              (may :olcReplogFile "olcReplogFile")
              (may :olcRequires "olcRequires")
              (may :olcRestrict "olcRestrict")
              (may :olcReverseLookup "olcReverseLookup")
              (may :olcRootDSE "olcRootDSE")
              (may :olcSaslAuxprops "olcSaslAuxprops")
              (may :olcSaslHost "olcSaslHost")
              (may :olcSaslRealm "olcSaslRealm")
              (may :olcSaslSecProps "olcSaslSecProps")
              (may :olcSecurity "olcSecurity")
              (may :olcServerID "olcServerID")
              (may :olcSizeLimit "olcSizeLimit")
              (may :olcSockbufMaxIncoming "olcSockbufMaxIncoming")
              (may :olcSockbufMaxIncomingAuth "olcSockbufMaxIncomingAuth")
              (may :olcTCPBuffer "olcTCPBuffer")
              (may :olcThreads "olcThreads")
              (may :olcTimeLimit "olcTimeLimit")
              (may :olcTLSCACertificateFile "olcTLSCACertificateFile")
              (may :olcTLSCACertificatePath "olcTLSCACertificatePath")
              (may :olcTLSCertificateFile "olcTLSCertificateFile")
              (may :olcTLSCertificateKeyFile "olcTLSCertificateKeyFile")
              (may :olcTLSCipherSuite "olcTLSCipherSuite")
              (may :olcTLSCRLCheck "olcTLSCRLCheck")
              (may :olcTLSRandFile "olcTLSRandFile")
              (may :olcTLSVerifyClient "olcTLSVerifyClient")
              (may :olcTLSDHParamFile "olcTLSDHParamFile")
              (may :olcTLSCRLFile "olcTLSCRLFile")
              (may :olcToolThreads "olcToolThreads")
              (may :olcWriteTimeout "olcWriteTimeout")
              (may :olcObjectIdentifier "olcObjectIdentifier")
              (may :olcAttributeTypes "olcAttributeTypes")
              (may :olcObjectClasses "olcObjectClasses")
              (may :olcDitContentRules "olcDitContentRules")
              (may :olcLdapSyntaxes "olcLdapSyntaxes"))

(object-class :olcSchemaConfig "olcSchemaConfig"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcObjectIdentifier "olcObjectIdentifier")
              (may :olcLdapSyntaxes "olcLdapSyntaxes")
              (may :olcAttributeTypes "olcAttributeTypes")
              (may :olcObjectClasses "olcObjectClasses")
              (may :olcDitContentRules "olcDitContentRules"))

(object-class :olcBackendConfig "olcBackendConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcBackend "olcBackend"))

(object-class :olcDatabaseConfig "olcDatabaseConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcDatabase "olcDatabase")
              (may :olcHidden "olcHidden")
              (may :olcSuffix "olcSuffix")
              (may :olcSubordinate "olcSubordinate")
              (may :olcAccess "olcAccess")
              (may :olcAddContentAcl "olcAddContentAcl")
              (may :olcLastMod "olcLastMod")
              (may :olcLimits "olcLimits")
              (may :olcMaxDerefDepth "olcMaxDerefDepth")
              (may :olcPlugin "olcPlugin")
              (may :olcReadOnly "olcReadOnly")
              (may :olcReplica "olcReplica")
              (may :olcReplicaArgsFile "olcReplicaArgsFile")
              (may :olcReplicaPidFile "olcReplicaPidFile")
              (may :olcReplicationInterval "olcReplicationInterval")
              (may :olcReplogFile "olcReplogFile")
              (may :olcRequires "olcRequires")
              (may :olcRestrict "olcRestrict")
              (may :olcRootDN "olcRootDN")
              (may :olcRootPW "olcRootPW")
              (may :olcSchemaDN "olcSchemaDN")
              (may :olcSecurity "olcSecurity")
              (may :olcSizeLimit "olcSizeLimit")
              (may :olcSyncUseSubentry "olcSyncUseSubentry")
              (may :olcSyncrepl "olcSyncrepl")
              (may :olcTimeLimit "olcTimeLimit")
              (may :olcUpdateDN "olcUpdateDN")
              (may :olcUpdateRef "olcUpdateRef")
              (may :olcMirrorMode "olcMirrorMode")
              (may :olcMonitoring "olcMonitoring")
              (may :olcExtraAttrs "olcExtraAttrs"))

(object-class :olcOverlayConfig "olcOverlayConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcOverlay "olcOverlay"))

(object-class :olcIncludeFile "olcIncludeFile"
              (superclass :olcConfig)
              (structural)
              (must :olcInclude "olcInclude")
              (may :cn "cn")
              (may :olcRootDSE "olcRootDSE"))

(object-class :olcFrontendConfig "olcFrontendConfig"
              (may :olcDefaultSearchBase "olcDefaultSearchBase")
              (may :olcPasswordHash "olcPasswordHash")
              (may :olcSortVals "olcSortVals"))

(object-class :olcModuleList "olcModuleList"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcModulePath "olcModulePath")
              (may :olcModuleLoad "olcModuleLoad"))

(object-class :olcLdifConfig "olcLdifConfig"
              (superclass :olcDatabaseConfig)
              (structural)
              (must :olcDbDirectory "olcDbDirectory"))

(object-class :olcBdbConfig "olcBdbConfig"
              (superclass :olcDatabaseConfig)
              (structural)
              (must :olcDbDirectory "olcDbDirectory")
              (may :olcDbCacheSize "olcDbCacheSize")
              (may :olcDbCheckpoint "olcDbCheckpoint")
              (may :olcDbConfig "olcDbConfig")
              (may :olcDbCryptFile "olcDbCryptFile")
              (may :olcDbCryptKey "olcDbCryptKey")
              (may :olcDbNoSync "olcDbNoSync")
              (may :olcDbDirtyRead "olcDbDirtyRead")
              (may :olcDbIDLcacheSize "olcDbIDLcacheSize")
              (may :olcDbIndex "olcDbIndex")
              (may :olcDbLinearIndex "olcDbLinearIndex")
              (may :olcDbLockDetect "olcDbLockDetect")
              (may :olcDbMode "olcDbMode")
              (may :olcDbSearchStack "olcDbSearchStack")
              (may :olcDbShmKey "olcDbShmKey")
              (may :olcDbCacheFree "olcDbCacheFree")
              (may :olcDbDNcacheSize "olcDbDNcacheSize")
              (may :olcDbPageSize "olcDbPageSize"))

(object-class :country "country"
              (superclass :top)
              (structural)
              (must :c "c")
              (may :searchGuide "searchGuide")
              (may :description "description"))

(object-class :locality "locality"
              (superclass :top)
              (structural)
              (may :street "street")
              (may :seeAlso "seeAlso")
              (may :searchGuide "searchGuide")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :organization "organization"
              (superclass :top)
              (structural)
              (must :o "o")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :organizationalUnit "organizationalUnit"
              (superclass :top)
              (structural)
              (must :ou "ou")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :person "person"
              (superclass :top)
              (structural)
              (must :sn "sn")
              (must :cn "cn")
              (may :userPassword "userPassword")
              (may :telephoneNumber "telephoneNumber")
              (may :seeAlso "seeAlso")
              (may :description "description"))

(object-class :organizationalPerson "organizationalPerson"
              (superclass :person)
              (structural)
              (may :title "title")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :ou "ou")
              (may :st "st")
              (may :l "l"))

(object-class :organizationalRole "organizationalRole"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :seeAlso "seeAlso")
              (may :roleOccupant "roleOccupant")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :ou "ou")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :groupOfNames "groupOfNames"
              (superclass :top)
              (structural)
              (must :member "member")
              (must :cn "cn")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :description "description"))

(object-class :residentialPerson "residentialPerson"
              (superclass :person)
              (structural)
              (must :l "l")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l"))

(object-class :applicationProcess "applicationProcess"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :seeAlso "seeAlso")
              (may :ou "ou")
              (may :l "l")
              (may :description "description"))

(object-class :applicationEntity "applicationEntity"
              (superclass :top)
              (structural)
              (must :presentationAddress "presentationAddress")
              (must :cn "cn")
              (may :supportedApplicationContext "supportedApplicationContext")
              (may :seeAlso "seeAlso")
              (may :ou "ou")
              (may :o "o")
              (may :l "l")
              (may :description "description"))

(object-class :dSA "dSA"
              (superclass :applicationEntity)
              (structural)
              (may :knowledgeInformation "knowledgeInformation"))

(object-class :device "device"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :serialNumber "serialNumber")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :l "l")
              (may :description "description"))

(object-class :strongAuthenticationUser "strongAuthenticationUser"
              (superclass :top)
              (must :userCertificate "userCertificate"))

(object-class :certificationAuthority "certificationAuthority"
              (superclass :top)
              (must :authorityRevocationList "authorityRevocationList")
              (must :certificateRevocationList "certificateRevocationList")
              (must :cACertificate "cACertificate")
              (may :crossCertificatePair "crossCertificatePair"))

(object-class :groupOfUniqueNames "groupOfUniqueNames"
              (superclass :top)
              (structural)
              (must :uniqueMember "uniqueMember")
              (must :cn "cn")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :description "description"))

(object-class :userSecurityInformation "userSecurityInformation"
              (superclass :top)
              (may :supportedAlgorithms "supportedAlgorithms"))

(object-class :certificationAuthority-V2 "certificationAuthority-V2"
              (superclass :certificationAuthority)
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :cRLDistributionPoint "cRLDistributionPoint"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :certificateRevocationList "certificateRevocationList")
              (may :authorityRevocationList "authorityRevocationList")
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :dmd "dmd"
              (superclass :top)
              (structural)
              (must :dmdName "dmdName")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :pkiUser "pkiUser"
              (superclass :top)
              (may :userCertificate "userCertificate"))

(object-class :pkiCA "pkiCA"
              (superclass :top)
              (may :authorityRevocationList "authorityRevocationList")
              (may :certificateRevocationList "certificateRevocationList")
              (may :cACertificate "cACertificate")
              (may :crossCertificatePair "crossCertificatePair"))

(object-class :deltaCRL "deltaCRL"
              (superclass :top)
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :labeledURIObject "labeledURIObject"
              (superclass :top)
              (may :labeledURI "labeledURI"))

(object-class :simpleSecurityObject "simpleSecurityObject"
              (superclass :top)
              (must :userPassword "userPassword"))

(object-class :dcObject "dcObject"
              (superclass :top)
              (must :dc "dc"))

(object-class :uidObject "uidObject"
              (superclass :top)
              (must :uid "uid"))

(object-class :pilotPerson "pilotPerson"
              (superclass :person)
              (structural)
              (may :textEncodedORAddress "textEncodedORAddress")
              (may :roomNumber "roomNumber")
              (may :userClass "userClass")
              (may :homePostalAddress "homePostalAddress")
              (may :secretary "secretary")
              (may :personalTitle "personalTitle")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :businessCategory "businessCategory")
              (may :janetMailbox "janetMailbox")
              (may :otherMailbox "otherMailbox")
              (may :organizationalStatus "organizationalStatus")
              (may :mailPreferenceOption "mailPreferenceOption")
              (may :personalSignature "personalSignature"))

(object-class :account "account"
              (superclass :top)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :host "host"))

(object-class :document "document"
              (superclass :top)
              (structural)
              (must :documentIdentifier "documentIdentifier")
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :documentTitle "documentTitle")
              (may :documentVersion "documentVersion")
              (may :documentAuthor "documentAuthor")
              (may :documentLocation "documentLocation")
              (may :documentPublisher "documentPublisher"))

(object-class :room "room"
              (superclass :top)
              (structural)
              (may :roomNumber "roomNumber")
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :telephoneNumber "telephoneNumber"))

(object-class :documentSeries "documentSeries"
              (superclass :top)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso"))

(object-class :domain "domain"
              (superclass :top)
              (structural)
              (may :associatedName "associatedName")
              (may :description "description")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :searchGuide "searchGuide")
              (may :userPassword "userPassword")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :postalAddress "postalAddress")
              (may :postalCode "postalCode")
              (may :postOfficeBox "postOfficeBox")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :telephoneNumber "telephoneNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telexNumber "telexNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :destinationIndicator "destinationIndicator")
              (may :registeredAddress "registeredAddress")
              (may :x121Address "x121Address"))

(object-class :RFC822localPart "RFC822localPart"
              (superclass :domain)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :telephoneNumber "telephoneNumber")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :postalAddress "postalAddress")
              (may :postalCode "postalCode")
              (may :postOfficeBox "postOfficeBox")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :telephoneNumber "telephoneNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telexNumber "telexNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :destinationIndicator "destinationIndicator")
              (may :registeredAddress "registeredAddress")
              (may :x121Address "x121Address"))

(object-class :dNSDomain "dNSDomain"
              (superclass :domain)
              (structural))

(object-class :domainRelatedObject "domainRelatedObject"
              (superclass :top)
              (must :associatedDomain "associatedDomain"))

(object-class :friendlyCountry "friendlyCountry"
              (superclass :country)
              (structural))

(object-class :pilotOrganization "pilotOrganization"
              (superclass :organization)
              (structural)
              (may :buildingName "buildingName"))

(object-class :pilotDSA "pilotDSA"
              (superclass :dsa)
              (structural)
              (may :dSAQuality "dSAQuality"))

(object-class :qualityLabelledData "qualityLabelledData"
              (superclass :top)
              (may :subtreeMinimumQuality "subtreeMinimumQuality")
              (may :subtreeMaximumQuality "subtreeMaximumQuality"))

(object-class :inetOrgPerson "inetOrgPerson"
              (superclass :organizationalPerson)
              (structural)
              (may :audio "audio")
              (may :businessCategory "businessCategory")
              (may :carLicense "carLicense")
              (may :departmentNumber "departmentNumber")
              (may :displayName "displayName")
              (may :employeeNumber "employeeNumber")
              (may :employeeType "employeeType")
              (may :givenName "givenName")
              (may :homePhone "homePhone")
              (may :homePostalAddress "homePostalAddress")
              (may :initials "initials")
              (may :jpegPhoto "jpegPhoto")
              (may :labeledURI "labeledURI")
              (may :mail "mail")
              (may :manager "manager")
              (may :mobile "mobile")
              (may :o "o")
              (may :pager "pager")
              (may :photo "photo")
              (may :roomNumber "roomNumber")
              (may :secretary "secretary")
              (may :uid "uid")
              (may :userCertificate "userCertificate")
              (may :preferredLanguage "preferredLanguage")
              (may :userSMIMECertificate "userSMIMECertificate")
              (may :userPKCS12 "userPKCS12"))

(object-class :GlueTop "GlueTop"
              (superclass :Top))

(object-class :GlueGeneralTop "GlueGeneralTop"
              (superclass :GlueTop))

(object-class :GlueInformationService "GlueInformationService"
              (superclass :GlueGeneralTop)
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueSchemaVersion "GlueSchemaVersion"
              (superclass :GlueGeneralTop)
              (must :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (must :GlueSchemaVersionMinor "GlueSchemaVersionMinor"))

(object-class :GlueKey "GlueKey"
              (superclass :GlueGeneralTop)
              (may :GlueChunkKey "GlueChunkKey")
              (may :GlueForeignKey "GlueForeignKey"))

(object-class :GlueService "GlueService"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueServiceUniqueID "GlueServiceUniqueID")
              (may :GlueServiceVersion "GlueServiceVersion")
              (may :GlueServiceName "GlueServiceName")
              (may :GlueServiceType "GlueServiceType")
              (may :GlueServiceEndpoint "GlueServiceEndpoint")
              (may :GlueServiceStatus "GlueServiceStatus")
              (may :GlueServiceStatusInfo "GlueServiceStatusInfo")
              (may :GlueServiceWSDL "GlueServiceWSDL")
              (may :GlueServiceSemantics "GlueServiceSemantics")
              (may :GlueServiceStartTime "GlueServiceStartTime")
              (may :GlueServiceOwner "GlueServiceOwner")
              (may :GlueServiceAccessPointURL "GlueServiceAccessPointURL")
              (may :GlueServicePrimaryOwnerName "GlueServicePrimaryOwnerName")
              (may :GlueServicePrimaryOwnerContact "GlueServicePrimaryOwnerContact")
              (may :GlueServiceHostingOrganization "GlueServiceHostingOrganization")
              (may :GlueServiceMajorVersion "GlueServiceMajorVersion")
              (may :GlueServiceMinorVersion "GlueServiceMinorVersion")
              (may :GlueServicePatchVersion "GlueServicePatchVersion")
              (may :GlueServiceInformationServiceURL "GlueServiceInformationServiceURL")
              (may :GlueServiceAccessControlRule "GlueServiceAccessControlRule")
              (may :GlueServiceURI "GlueServiceURI")
              (may :GlueServiceAccessControlBaseRule "GlueServiceAccessControlBaseRule")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor")
              (may :GlueInformationServiceURL "GlueInformationServiceURL")
              (may :GlueForeignKey "GlueForeignKey"))

(object-class :GlueServiceData "GlueServiceData"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueServiceDataKey "GlueServiceDataKey")
              (may :GlueServiceDataValue "GlueServiceDataValue")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueSite "GlueSite"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueSiteUniqueID "GlueSiteUniqueID")
              (may :GlueSiteDescription "GlueSiteDescription")
              (may :GlueSiteName "GlueSiteName")
              (may :GlueSiteUserSupportContact "GlueSiteUserSupportContact")
              (may :GlueSiteSysAdminContact "GlueSiteSysAdminContact")
              (may :GlueSiteSecurityContact "GlueSiteSecurityContact")
              (may :GlueSiteLocation "GlueSiteLocation")
              (may :GlueSiteLatitude "GlueSiteLatitude")
              (may :GlueSiteLongitude "GlueSiteLongitude")
              (may :GlueSiteWeb "GlueSiteWeb")
              (may :GlueSiteSponsor "GlueSiteSponsor")
              (may :GlueSiteOtherInfo "GlueSiteOtherInfo")
              (may :GlueSiteEmailContact "GlueSiteEmailContact")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor"))

(object-class :Mds "Mds"
              (structural)
              (may :Mds-validfrom "Mds-validfrom")
              (may :Mds-validto "Mds-validto")
              (may :Mds-keepto "Mds-keepto")
              (may :Mds-Vo-name "Mds-Vo-name"))

(object-class :GlueCETop "GlueCETop"
              (superclass :GlueTop))

(object-class :GlueClusterTop "GlueClusterTop"
              (superclass :GlueTop))

(object-class :GlueCEInfo "GlueCEInfo"
              (superclass :GlueCETop)
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEInfoLRMSType "GlueCEInfoLRMSType")
              (may :GlueCEInfoLRMSVersion "GlueCEInfoLRMSVersion")
              (may :GlueCEInfoGRAMVersion "GlueCEInfoGRAMVersion")
              (may :GlueCEInfoHostName "GlueCEInfoHostName")
              (may :GlueCEInfoGatekeeperPort "GlueCEInfoGatekeeperPort")
              (may :GlueCEInfoContactString "GlueCEInfoContactString")
              (may :GlueCEInfoJobManager "GlueCEInfoJobManager")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE"))

(object-class :GlueCEState "GlueCEState"
              (superclass :GlueCETop)
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots"))

(object-class :GlueCEPolicy "GlueCEPolicy"
              (superclass :GlueCETop)
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption"))

(object-class :GlueCEAccessControlBase "GlueCEAccessControlBase"
              (superclass :GlueCETop)
              (must :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule"))

(object-class :GlueCEJob "GlueCEJob"
              (superclass :GlueCETop)
              (structural)
              (must :GlueCEJobGlobalID "GlueCEJobGlobalID")
              (may :GlueCEJobLocalOwner "GlueCEJobLocalOwner")
              (may :GlueCEJobGlobalOwner "GlueCEJobGlobalOwner")
              (may :GlueCEJobStatus "GlueCEJobStatus")
              (may :GlueCEJobSchedulerSpecific "GlueCEJobSchedulerSpecific")
              (may :GlueCEJobLocalID "GlueCEJobLocalID"))

(object-class :GlueCluster "GlueCluster"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueClusterUniqueID "GlueClusterUniqueID")
              (may :GlueClusterName "GlueClusterName")
              (may :GlueClusterService "GlueClusterService")
              (may :GlueCEUniqueID "GlueCEUniqueID")
              (may :GlueClusterTmpDir "GlueClusterTmpDir")
              (may :GlueClusterWNTmpDir "GlueClusterWNTmpDir")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueHost "GlueHost"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostUniqueID "GlueHostUniqueID")
              (may :GlueHostName "GlueHostName"))

(object-class :GlueHostArchitecture "GlueHostArchitecture"
              (superclass :GlueClusterTop)
              (may :GlueHostArchitecturePlatformType "GlueHostArchitecturePlatformType")
              (may :GlueHostArchitectureSMPSize "GlueHostArchitectureSMPSize"))

(object-class :GlueHostProcessor "GlueHostProcessor"
              (superclass :GlueClusterTop)
              (may :GlueHostProcessorVendor "GlueHostProcessorVendor")
              (may :GlueHostProcessorModel "GlueHostProcessorModel")
              (may :GlueHostProcessorVersion "GlueHostProcessorVersion")
              (may :GlueHostProcessorClockSpeed "GlueHostProcessorClockSpeed")
              (may :GlueHostProcessorInstructionSet "GlueHostProcessorInstructionSet")
              (may :GlueHostProcessorOtherDescription "GlueHostProcessorOtherDescription")
              (may :GlueHostProcessorCacheL1 "GlueHostProcessorCacheL1")
              (may :GlueHostProcessorCacheL1I "GlueHostProcessorCacheL1I")
              (may :GlueHostProcessorCacheL1D "GlueHostProcessorCacheL1D")
              (may :GlueHostProcessorCacheL2 "GlueHostProcessorCacheL2"))

(object-class :GlueHostApplicationSoftware "GlueHostApplicationSoftware"
              (superclass :GlueClusterTop)
              (may :GlueHostApplicationSoftwareRunTimeEnvironment "GlueHostApplicationSoftwareRunTimeEnvironment"))

(object-class :GlueHostMainMemory "GlueHostMainMemory"
              (superclass :GlueClusterTop)
              (may :GlueHostMainMemoryRAMSize "GlueHostMainMemoryRAMSize")
              (may :GlueHostMainMemoryRAMAvailable "GlueHostMainMemoryRAMAvailable")
              (may :GlueHostMainMemoryVirtualSize "GlueHostMainMemoryVirtualSize")
              (may :GlueHostMainMemoryVirtualAvailable "GlueHostMainMemoryVirtualAvailable"))

(object-class :GlueHostBenchmark "GlueHostBenchmark"
              (superclass :GlueClusterTop)
              (may :GlueHostBenchmarkSI00 "GlueHostBenchmarkSI00")
              (may :GlueHostBenchmarkSF00 "GlueHostBenchmarkSF00"))

(object-class :GlueHostNetworkAdapter "GlueHostNetworkAdapter"
              (superclass :GlueClusterTop)
              (may :GlueHostNetworkAdapterOutboundIP "GlueHostNetworkAdapterOutboundIP")
              (may :GlueHostNetworkAdapterInboundIP "GlueHostNetworkAdapterInboundIP")
              (may :GlueHostNetworkAdapterName "GlueHostNetworkAdapterName")
              (may :GlueHostNetworkAdapterIPAddress "GlueHostNetworkAdapterIPAddress")
              (may :GlueHostNetworkAdapterMTU "GlueHostNetworkAdapterMTU"))

(object-class :GlueHostProcessorLoad "GlueHostProcessorLoad"
              (superclass :GlueClusterTop)
              (may :GlueHostProcessorLoadLast1Min "GlueHostProcessorLoadLast1Min")
              (may :GlueHostProcessorLoadLast5Min "GlueHostProcessorLoadLast5Min")
              (may :GlueHostProcessorLoadLast15Min "GlueHostProcessorLoadLast15Min"))

(object-class :GlueHostSMPLoad "GlueHostSMPLoad"
              (superclass :GlueClusterTop)
              (may :GlueHostSMPLoadLast1Min "GlueHostSMPLoadLast1Min")
              (may :GlueHostSMPLoadLast5Min "GlueHostSMPLoadLast5Min")
              (may :GlueHostSMPLoadLast15Min "GlueHostSMPLoadLast15Min"))

(object-class :GlueHostOperatingSystem "GlueHostOperatingSystem"
              (superclass :GlueClusterTop)
              (may :GlueHostOperatingSystemName "GlueHostOperatingSystemName")
              (may :GlueHostOperatingSystemRelease "GlueHostOperatingSystemRelease")
              (may :GlueHostOperatingSystemVersion "GlueHostOperatingSystemVersion"))

(object-class :GlueHostLocalFileSystem "GlueHostLocalFileSystem"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostLocalFileSystemName "GlueHostLocalFileSystemName")
              (may :GlueHostLocalFileSystemRoot "GlueHostLocalFileSystemRoot")
              (may :GlueHostLocalFileSystemSize "GlueHostLocalFileSystemSize")
              (may :GlueHostLocalFileSystemAvailableSpace "GlueHostLocalFileSystemAvailableSpace")
              (may :GlueHostLocalFileSystemReadOnly "GlueHostLocalFileSystemReadOnly")
              (may :GlueHostLocalFileSystemType "GlueHostLocalFileSystemType")
              (may :GlueHostLocalFileSystemClient "GlueHostLocalFileSystemClient"))

(object-class :GlueHostRemoteFileSystem "GlueHostRemoteFileSystem"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostRemoteFileSystemName "GlueHostRemoteFileSystemName")
              (may :GlueHostRemoteFileSystemRoot "GlueHostRemoteFileSystemRoot")
              (may :GlueHostRemoteFileSystemSize "GlueHostRemoteFileSystemSize")
              (may :GlueHostRemoteFileSystemAvailableSpace "GlueHostRemoteFileSystemAvailableSpace")
              (may :GlueHostRemoteFileSystemReadOnly "GlueHostRemoteFileSystemReadOnly")
              (may :GlueHostRemoteFileSystemType "GlueHostRemoteFileSystemType")
              (may :GlueHostRemoteFileSystemName "GlueHostRemoteFileSystemName")
              (may :GlueHostRemoteFileSystemServer "GlueHostRemoteFileSystemServer"))

(object-class :GlueHostStorageDevice "GlueHostStorageDevice"
              (superclass :GlueClusterTop)
              (must :GlueHostStorageDeviceName "GlueHostStorageDeviceName")
              (may :GlueHostStorageDeviceType "GlueHostStorageDeviceType")
              (may :GlueHostStorageDeviceTransferRate "GlueHostStorageDeviceTransferRate")
              (may :GlueHostStorageDeviceSize "GlueHostStorageDeviceSize")
              (may :GlueHostStorageDeviceAvailableSpace "GlueHostStorageDeviceAvailableSpace"))

(object-class :GlueHostFile "GlueHostFile"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostFileName "GlueHostFileName")
              (may :GlueHostFileSize "GlueHostFileSize")
              (may :GlueHostFileCreationDate "GlueHostFileCreationDate")
              (may :GlueHostFileLastModified "GlueHostFileLastModified")
              (may :GlueHostFileLastAccessed "GlueHostFileLastAccessed")
              (may :GlueHostFileLatency "GlueHostFileLatency")
              (may :GlueHostFileLifeTime "GlueHostFileLifeTime")
              (may :GlueHostFileOwner "GlueHostFileOwner"))

(object-class :GlueLocation "GlueLocation"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueLocationLocalID "GlueLocationLocalID")
              (may :GlueLocationName "GlueLocationName")
              (may :GlueLocationPath "GlueLocationPath")
              (may :GlueLocationVersion "GlueLocationVersion"))

(object-class :GlueVOView "GlueVOView"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueVOViewLocalID "GlueVOViewLocalID")
              (may :GlueCECapability "GlueCECapability")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE")
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeCPUs "GlueCEStateFreeCPUs")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots")
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption")
              (may :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule"))

(object-class :GlueSoftware "GlueSoftware"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSoftwareLocalID "GlueSoftwareLocalID")
              (may :GlueSoftwareName "GlueSoftwareName")
              (may :GlueSoftwareVersion "GlueSoftwareVersion")
              (may :GlueSoftwareInstalledRoot "GlueSoftwareInstalledRoot")
              (may :GlueSoftwareEnvironmentSetup "GlueSoftwareEnvironmentSetup")
              (may :GlueSoftwareModuleName "GlueSoftwareModuleName"))

(object-class :GlueSoftwareData "GlueSoftwareData"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSoftwareDataKey "GlueSoftwareDataKey")
              (may :GlueSoftwareDataValue "GlueSoftwareDataValue"))

(object-class :GlueCE "GlueCE"
              (superclass :GlueCETop)
              (structural)
              (must :GlueCEUniqueID "GlueCEUniqueID")
              (may :GlueCEName "GlueCEName")
              (may :GlueCEHostingCluster "GlueCEHostingCluster")
              (may :GlueSiteUniqueID "GlueSiteUniqueID")
              (may :GlueCEImplementationName "GlueCEImplementationName")
              (may :GlueCEImplementationVersion "GlueCEImplementationVersion")
              (may :GlueCECapability "GlueCECapability")
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEInfoLRMSType "GlueCEInfoLRMSType")
              (may :GlueCEInfoLRMSVersion "GlueCEInfoLRMSVersion")
              (may :GlueCEInfoGRAMVersion "GlueCEInfoGRAMVersion")
              (may :GlueCEInfoHostName "GlueCEInfoHostName")
              (may :GlueCEInfoGatekeeperPort "GlueCEInfoGatekeeperPort")
              (may :GlueCEInfoContactString "GlueCEInfoContactString")
              (may :GlueCEInfoJobManager "GlueCEInfoJobManager")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE")
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots")
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption")
              (may :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueSubCluster "GlueSubCluster"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSubClusterUniqueID "GlueSubClusterUniqueID")
              (may :GlueSubClusterName "GlueSubClusterName")
              (may :GlueSubClusterWNTmpDir "GlueSubClusterWNTmpDir")
              (may :GlueSubClusterTmpDir "GlueSubClusterTmpDir")
              (may :GlueSubClusterPhysicalCPUs "GlueSubClusterPhysicalCPUs")
              (may :GlueSubClusterLogicalCPUs "GlueSubClusterLogicalCPUs")
              (may :GlueHostOperatingSystemName "GlueHostOperatingSystemName")
              (may :GlueHostOperatingSystemRelease "GlueHostOperatingSystemRelease")
              (may :GlueHostOperatingSystemVersion "GlueHostOperatingSystemVersion")
              (may :GlueHostArchitecturePlatformType "GlueHostArchitecturePlatformType")
              (may :GlueHostArchitectureSMPSize "GlueHostArchitectureSMPSize")
              (may :GlueHostProcessorVendor "GlueHostProcessorVendor")
              (may :GlueHostProcessorModel "GlueHostProcessorModel")
              (may :GlueHostProcessorVersion "GlueHostProcessorVersion")
              (may :GlueHostProcessorClockSpeed "GlueHostProcessorClockSpeed")
              (may :GlueHostProcessorInstructionSet "GlueHostProcessorInstructionSet")
              (may :GlueHostProcessorOtherDescription "GlueHostProcessorOtherDescription")
              (may :GlueHostApplicationSoftwareRunTimeEnvironment "GlueHostApplicationSoftwareRunTimeEnvironment")
              (may :GlueHostBenchmarkSI00 "GlueHostBenchmarkSI00")
              (may :GlueHostBenchmarkSF00 "GlueHostBenchmarkSF00")
              (may :GlueHostNetworkAdapterOutboundIP "GlueHostNetworkAdapterOutboundIP")
              (may :GlueHostNetworkAdapterInboundIP "GlueHostNetworkAdapterInboundIP")
              (may :GlueHostMainMemoryRAMSize "GlueHostMainMemoryRAMSize")
              (may :GlueHostMainMemoryVirtualSize "GlueHostMainMemoryVirtualSize"))

(object-class :GlueCESEBindGroup "GlueCESEBindGroup"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueCESEBindGroupCEUniqueID "GlueCESEBindGroupCEUniqueID")
              (may :GlueCESEBindGroupSEUniqueID "GlueCESEBindGroupSEUniqueID"))

(object-class :GlueCESEBind "GlueCESEBind"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueCESEBindCEUniqueID "GlueCESEBindCEUniqueID")
              (must :GlueCESEBindSEUniqueID "GlueCESEBindSEUniqueID")
              (may :GlueCESEBindCEAccesspoint "GlueCESEBindCEAccesspoint")
              (may :GlueCESEBindMountInfo "GlueCESEBindMountInfo")
              (may :GlueCESEBindWeight "GlueCESEBindWeight"))

(object-class :GlueSETop "GlueSETop"
              (superclass :GlueTop))

(object-class :GlueSLTop "GlueSLTop"
              (superclass :GlueTop))

(object-class :GlueSATop "GlueSATop"
              (superclass :GlueTop))

(object-class :GlueSEState "GlueSEState"
              (superclass :GlueSETop)
              (may :GlueSEStateCurrentIOLoad "GlueSEStateCurrentIOLoad"))

(object-class :GlueSEAccessProtocol "GlueSEAccessProtocol"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEAccessProtocolLocalID "GlueSEAccessProtocolLocalID")
              (may :GlueSEAccessProtocolPort "GlueSEAccessProtocolPort")
              (may :GlueSEAccessProtocolVersion "GlueSEAccessProtocolVersion")
              (may :GlueSEAccessProtocolSupportedSecurity "GlueSEAccessProtocolSupportedSecurity")
              (may :GlueSEAccessProtocolAccessTime "GlueSEAccessProtocolAccessTime")
              (may :GlueSEAccessProtocolEndpoint "GlueSEAccessProtocolEndpoint")
              (may :GlueSEAccessProtocolCapability "GlueSEAccessProtocolCapability")
              (may :GlueSEAccessProtocolType "GlueSEAccessProtocolType")
              (may :GlueSEAccessProtocolMaxStreams "GlueSEAccessProtocolMaxStreams")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueSEControlProtocol "GlueSEControlProtocol"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEControlProtocolLocalID "GlueSEControlProtocolLocalID")
              (may :GlueSEControlProtocolVersion "GlueSEControlProtocolVersion")
              (may :GlueSEControlProtocolEndpoint "GlueSEControlProtocolEndpoint")
              (may :GlueSEControlProtocolCapability "GlueSEControlProtocolCapability")
              (may :GlueSEControlProtocolType "GlueSEControlProtocolType")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueSL "GlueSL"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLUniqueID "GlueSLUniqueID")
              (may :GlueSLName "GlueSLName")
              (may :GlueSLService "GlueSLService"))

(object-class :GlueSLLocalFileSystem "GlueSLLocalFileSystem"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLLocalFileSystemName "GlueSLLocalFileSystemName")
              (may :GlueSLLocalFileSystemRoot "GlueSLLocalFileSystemRoot")
              (may :GlueSLLocalFileSystemSize "GlueSLLocalFileSystemSize")
              (may :GlueSLLocalFileSystemAvailableSpace "GlueSLLocalFileSystemAvailableSpace")
              (may :GlueSLLocalFileSystemReadOnly "GlueSLLocalFileSystemReadOnly")
              (may :GlueSLLocalFileSystemType "GlueSLLocalFileSystemType")
              (may :GlueSLLocalFileSystemClient "GlueSLLocalFileSystemClient"))

(object-class :GlueSLRemoteFileSystem "GlueSLRemoteFileSystem"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLRemoteFileSystemName "GlueSLRemoteFileSystemName")
              (may :GlueSLRemoteFileSystemRoot "GlueSLRemoteFileSystemRoot")
              (may :GlueSLRemoteFileSystemSize "GlueSLRemoteFileSystemSize")
              (may :GlueSLRemoteFileSystemAvailableSpace "GlueSLRemoteFileSystemAvailableSpace")
              (may :GlueSLRemoteFileSystemReadOnly "GlueSLRemoteFileSystemReadOnly")
              (may :GlueSLRemoteFileSystemType "GlueSLRemoteFileSystemType")
              (may :GlueSLRemoteFileSystemName "GlueSLRemoteFileSystemName")
              (may :GlueSLRemoteFileSystemServer "GlueSLRemoteFileSystemServer"))

(object-class :GlueSLFile "GlueSLFile"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLFileName "GlueSLFileName")
              (may :GlueSLFileSize "GlueSLFileSize")
              (may :GlueSLFileCreationDate "GlueSLFileCreationDate")
              (may :GlueSLFileLastModified "GlueSLFileLastModified")
              (may :GlueSLFileLastAccessed "GlueSLFileLastAccessed")
              (may :GlueSLFileLatency "GlueSLFileLatency")
              (may :GlueSLFileLifeTime "GlueSLFileLifeTime")
              (may :GlueSLFilePath "GlueSLFilePath"))

(object-class :GlueSLDirectory "GlueSLDirectory"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLDirectoryName "GlueSLDirectoryName")
              (may :GlueSLDirectorySize "GlueSLDirectorySize")
              (may :GlueSLDirectoryCreationDate "GlueSLDirectoryCreationDate")
              (may :GlueSLDirectoryLastModified "GlueSLDirectoryLastModified")
              (may :GlueSLDirectoryLastAccessed "GlueSLDirectoryLastAccessed")
              (may :GlueSLDirectoryLatency "GlueSLDirectoryLatency")
              (may :GlueSLDirectoryLifeTime "GlueSLDirectoryLifeTime")
              (may :GlueSLDirectoryPath "GlueSLDirectoryPath"))

(object-class :GlueSLArchitecture "GlueSLArchitecture"
              (superclass :GlueSLTop)
              (may :GlueSLArchitectureType "GlueSLArchitectureType"))

(object-class :GlueSLPerformance "GlueSLPerformance"
              (superclass :GlueSLTop)
              (may :GlueSLPerformanceMaxIOCapacity "GlueSLPerformanceMaxIOCapacity"))

(object-class :GlueSAPolicy "GlueSAPolicy"
              (superclass :GlueSATop)
              (may :GlueSAPolicyMaxFileSize "GlueSAPolicyMaxFileSize")
              (may :GlueSAPolicyMinFileSize "GlueSAPolicyMinFileSize")
              (may :GlueSAPolicyMaxData "GlueSAPolicyMaxData")
              (may :GlueSAPolicyMaxNumFiles "GlueSAPolicyMaxNumFiles")
              (may :GlueSAPolicyMaxPinDuration "GlueSAPolicyMaxPinDuration")
              (may :GlueSAPolicyQuota "GlueSAPolicyQuota")
              (may :GlueSAPolicyFileLifeTime "GlueSAPolicyFileLifeTime"))

(object-class :GlueSAState "GlueSAState"
              (superclass :GlueSATop)
              (may :GlueSAStateAvailableSpace "GlueSAStateAvailableSpace")
              (may :GlueSAStateUsedSpace "GlueSAStateUsedSpace"))

(object-class :GlueSAAccessControlBase "GlueSAAccessControlBase"
              (superclass :GlueSATop)
              (may :GlueSAAccessControlBaseRule "GlueSAAccessControlBaseRule"))

(object-class :GlueVOInfo "GlueVOInfo"
              (superclass :GlueSATop)
              (structural)
              (must :GlueVOInfoLocalID "GlueVOInfoLocalID")
              (may :GlueVOInfoName "GlueVOInfoName")
              (may :GlueVOInfoPath "GlueVOInfoPath")
              (may :GlueVOInfoTag "GlueVOInfoTag")
              (may :GlueVOInfoAccessControlBaseRule "GlueVOInfoAccessControlBaseRule"))

(object-class :GlueSA "GlueSA"
              (superclass :GlueSATop)
              (structural)
              (must :GlueSALocalID "GlueSALocalID")
              (may :GlueSARoot "GlueSARoot")
              (may :GlueSAPath "GlueSAPath")
              (may :GlueSAType "GlueSAType")
              (may :GlueSAUniqueID "GlueSAUniqueID")
              (may :GlueSAName "GlueSAName")
              (may :GlueSATotalOnlineSize "GlueSATotalOnlineSize")
              (may :GlueSAFreeOnlineSize "GlueSAFreeOnlineSize")
              (may :GlueSAUsedOnlineSize "GlueSAUsedOnlineSize")
              (may :GlueSAReservedOnlineSize "GlueSAReservedOnlineSize")
              (may :GlueSATotalNearlineSize "GlueSATotalNearlineSize")
              (may :GlueSAFreeNearlineSize "GlueSAFreeNearlineSize")
              (may :GlueSAUsedNearlineSize "GlueSAUsedNearlineSize")
              (may :GlueSAReservedNearlineSize "GlueSAReservedNearlineSize")
              (may :GlueSARetentionPolicy "GlueSARetentionPolicy")
              (may :GlueSAAccessLatency "GlueSAAccessLatency")
              (may :GlueSAExpirationMode "GlueSAExpirationMode")
              (may :GlueSACapability "GlueSACapability")
              (may :GlueSAStateAvailableSpace "GlueSAStateAvailableSpace")
              (may :GlueSAStateUsedSpace "GlueSAStateUsedSpace")
              (may :GlueSAAccessControlBaseRule "GlueSAAccessControlBaseRule")
              (may :GlueChunkKey "GlueChunkKey")
              (may :GlueSAPolicyMaxFileSize "GlueSAPolicyMaxFileSize")
              (may :GlueSAPolicyMinFileSize "GlueSAPolicyMinFileSize")
              (may :GlueSAPolicyMaxData "GlueSAPolicyMaxData")
              (may :GlueSAPolicyMaxNumFiles "GlueSAPolicyMaxNumFiles")
              (may :GlueSAPolicyMaxPinDuration "GlueSAPolicyMaxPinDuration")
              (may :GlueSAPolicyQuota "GlueSAPolicyQuota")
              (may :GlueSAPolicyFileLifeTime "GlueSAPolicyFileLifeTime"))

(object-class :GlueSE "GlueSE"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEUniqueID "GlueSEUniqueID")
              (may :GlueSEName "GlueSEName")
              (may :GlueSEPort "GlueSEPort")
              (may :GlueSEHostingSL "GlueSEHostingSL")
              (may :GlueSESizeTotal "GlueSESizeTotal")
              (may :GlueSESizeFree "GlueSESizeFree")
              (may :GlueSEArchitecture "GlueSEArchitecture")
              (may :GlueSEType "GlueSEType")
              (may :GlueSEImplementationName "GlueSEImplementationName")
              (may :GlueSEImplementationVersion "GlueSEImplementationVersion")
              (may :GlueSEStatus "GlueSEStatus")
              (may :GlueSETotalOnlineSize "GlueSETotalOnlineSize")
              (may :GlueSETotalNearlineSize "GlueSETotalNearlineSize")
              (may :GlueSEUsedOnlineSize "GlueSEUsedOnlineSize")
              (may :GlueSEUsedNearlineSize "GlueSEUsedNearlineSize")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor")
              (may :GlueSEStateCurrentIOLoad "GlueSEStateCurrentIOLoad")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GLUE2Group "GLUE2Group"
              (structural)
              (must :GLUE2GroupID "GLUE2GroupID"))

(object-class :GLUE2Entity "GLUE2Entity"
              (may :GLUE2EntityName "GLUE2EntityName")
              (may :GLUE2EntityOtherInfo "GLUE2EntityOtherInfo")
              (may :GLUE2EntityCreationTime "GLUE2EntityCreationTime")
              (may :GLUE2EntityValidity "GLUE2EntityValidity"))

(object-class :GLUE2Extension "GLUE2Extension"
              (structural)
              (must :GLUE2ExtensionKey "GLUE2ExtensionKey")
              (must :GLUE2ExtensionValue "GLUE2ExtensionValue")
              (must :GLUE2ExtensionEntityForeignKey "GLUE2ExtensionEntityForeignKey"))

(object-class :GLUE2Location "GLUE2Location"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2LocationID "GLUE2LocationID")
              (may :GLUE2LocationAddress "GLUE2LocationAddress")
              (may :GLUE2LocationPlace "GLUE2LocationPlace")
              (may :GLUE2LocationCountry "GLUE2LocationCountry")
              (may :GLUE2LocationPostCode "GLUE2LocationPostCode")
              (may :GLUE2LocationLatitude "GLUE2LocationLatitude")
              (may :GLUE2LocationLongitude "GLUE2LocationLongitude")
              (may :GLUE2LocationServiceForeignKey "GLUE2LocationServiceForeignKey")
              (may :GLUE2LocationDomainForeignKey "GLUE2LocationDomainForeignKey"))

(object-class :GLUE2Contact "GLUE2Contact"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ContactID "GLUE2ContactID")
              (must :GLUE2ContactDetail "GLUE2ContactDetail")
              (must :GLUE2ContactType "GLUE2ContactType")
              (may :GLUE2ContactServiceForeignKey "GLUE2ContactServiceForeignKey")
              (may :GLUE2ContactDomainForeignKey "GLUE2ContactDomainForeignKey"))

(object-class :GLUE2Domain "GLUE2Domain"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2DomainID "GLUE2DomainID")
              (may :GLUE2DomainDescription "GLUE2DomainDescription")
              (may :GLUE2DomainWWW "GLUE2DomainWWW"))

(object-class :GLUE2AdminDomain "GLUE2AdminDomain"
              (superclass :GLUE2Domain)
              (may :GLUE2AdminDomainDistributed "GLUE2AdminDomainDistributed")
              (may :GLUE2AdminDomainOwner "GLUE2AdminDomainOwner")
              (may :GLUE2AdminDomainAdminDomainForeignKey "GLUE2AdminDomainAdminDomainForeignKey"))

(object-class :GLUE2UserDomain "GLUE2UserDomain"
              (superclass :GLUE2Domain)
              (may :GLUE2UserDomainLevel "GLUE2UserDomainLevel")
              (may :GLUE2UserDomainUserManager "GLUE2UserDomainUserManager")
              (may :GLUE2UserDomainMember "GLUE2UserDomainMember")
              (may :GLUE2UserDomainUserDomainForeignKey "GLUE2UserDomainUserDomainForeignKey"))

(object-class :GLUE2Service "GLUE2Service"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ServiceID "GLUE2ServiceID")
              (must :GLUE2ServiceType "GLUE2ServiceType")
              (must :GLUE2ServiceQualityLevel "GLUE2ServiceQualityLevel")
              (must :GLUE2ServiceAdminDomainForeignKey "GLUE2ServiceAdminDomainForeignKey")
              (may :GLUE2ServiceCapability "GLUE2ServiceCapability")
              (may :GLUE2ServiceStatusInfo "GLUE2ServiceStatusInfo")
              (may :GLUE2ServiceComplexity "GLUE2ServiceComplexity")
              (may :GLUE2ServiceServiceForeignKey "GLUE2ServiceServiceForeignKey"))

(object-class :GLUE2Endpoint "GLUE2Endpoint"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2EndpointID "GLUE2EndpointID")
              (must :GLUE2EndpointURL "GLUE2EndpointURL")
              (must :GLUE2EndpointInterfaceName "GLUE2EndpointInterfaceName")
              (must :GLUE2EndpointQualityLevel "GLUE2EndpointQualityLevel")
              (must :GLUE2EndpointHealthState "GLUE2EndpointHealthState")
              (must :GLUE2EndpointServingState "GLUE2EndpointServingState")
              (must :GLUE2EndpointServiceForeignKey "GLUE2EndpointServiceForeignKey")
              (may :GLUE2EndpointCapability "GLUE2EndpointCapability")
              (may :GLUE2EndpointTechnology "GLUE2EndpointTechnology")
              (may :GLUE2EndpointInterfaceVersion "GLUE2EndpointInterfaceVersion")
              (may :GLUE2EndpointInterfaceExtension "GLUE2EndpointInterfaceExtension")
              (may :GLUE2EndpointWSDL "GLUE2EndpointWSDL")
              (may :GLUE2EndpointSupportedProfile "GLUE2EndpointSupportedProfile")
              (may :GLUE2EndpointSemantics "GLUE2EndpointSemantics")
              (may :GLUE2EndpointImplementor "GLUE2EndpointImplementor")
              (may :GLUE2EndpointImplementationName "GLUE2EndpointImplementationName")
              (may :GLUE2EndpointImplementationVersion "GLUE2EndpointImplementationVersion")
              (may :GLUE2EndpointHealthStateInfo "GLUE2EndpointHealthStateInfo")
              (may :GLUE2EndpointStartTime "GLUE2EndpointStartTime")
              (may :GLUE2EndpointIssuerCA "GLUE2EndpointIssuerCA")
              (may :GLUE2EndpointTrustedCA "GLUE2EndpointTrustedCA")
              (may :GLUE2EndpointDowntimeAnnounce "GLUE2EndpointDowntimeAnnounce")
              (may :GLUE2EndpointDowntimeStart "GLUE2EndpointDowntimeStart")
              (may :GLUE2EndpointDowntimeEnd "GLUE2EndpointDowntimeEnd")
              (may :GLUE2EndpointDowntimeInfo "GLUE2EndpointDowntimeInfo"))

(object-class :GLUE2Share "GLUE2Share"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ShareID "GLUE2ShareID")
              (must :GLUE2ShareServiceForeignKey "GLUE2ShareServiceForeignKey")
              (may :GLUE2ShareDescription "GLUE2ShareDescription")
              (may :GLUE2ShareEndpointForeignKey "GLUE2ShareEndpointForeignKey")
              (may :GLUE2ShareResourceForeignKey "GLUE2ShareResourceForeignKey"))

(object-class :GLUE2Manager "GLUE2Manager"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ManagerID "GLUE2ManagerID")
              (must :GLUE2ManagerProductName "GLUE2ManagerProductName")
              (must :GLUE2ManagerServiceForeignKey "GLUE2ManagerServiceForeignKey")
              (may :GLUE2ManagerProductVersion "GLUE2ManagerProductVersion"))

(object-class :GLUE2Resource "GLUE2Resource"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ResourceID "GLUE2ResourceID")
              (must :GLUE2ResourceManagerForeignKey "GLUE2ResourceManagerForeignKey"))

(object-class :GLUE2Activity "GLUE2Activity"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ActivityID "GLUE2ActivityID")
              (may :GLUE2ActivityUserDomainForeignKey "GLUE2ActivityUserDomainForeignKey")
              (may :GLUE2ActivityEndpointForeignKey "GLUE2ActivityEndpointForeignKey")
              (may :GLUE2ActivityShareForeignKey "GLUE2ActivityShareForeignKey")
              (may :GLUE2ActivityResourceForeignKey "GLUE2ActivityResourceForeignKey")
              (may :GLUE2ActivityActivityForeignKey "GLUE2ActivityActivityForeignKey"))

(object-class :GLUE2Policy "GLUE2Policy"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2PolicyID "GLUE2PolicyID")
              (must :GLUE2PolicyScheme "GLUE2PolicyScheme")
              (must :GLUE2PolicyRule "GLUE2PolicyRule")
              (may :GLUE2PolicyUserDomainForeignKey "GLUE2PolicyUserDomainForeignKey"))

(object-class :GLUE2AccessPolicy "GLUE2AccessPolicy"
              (must :GLUE2AccessPolicyEndpointForeignKey "GLUE2AccessPolicyEndpointForeignKey"))

(object-class :GLUE2MappingPolicy "GLUE2MappingPolicy"
              (must :GLUE2MappingPolicyShareForeignKey "GLUE2MappingPolicyShareForeignKey"))

(object-class :GLUE2ComputingService "GLUE2ComputingService"
              (may :GLUE2ComputingServiceTotalJobs "GLUE2ComputingServiceTotalJobs")
              (may :GLUE2ComputingServiceRunningJobs "GLUE2ComputingServiceRunningJobs")
              (may :GLUE2ComputingServiceWaitingJobs "GLUE2ComputingServiceWaitingJobs")
              (may :GLUE2ComputingServiceStagingJobs "GLUE2ComputingServiceStagingJobs")
              (may :GLUE2ComputingServiceSuspendedJobs "GLUE2ComputingServiceSuspendedJobs")
              (may :GLUE2ComputingServicePreLRMSWaitingJobs "GLUE2ComputingServicePreLRMSWaitingJobs"))

(object-class :GLUE2ComputingEndpoint "GLUE2ComputingEndpoint"
              (may :GLUE2ComputingEndpointStaging "GLUE2ComputingEndpointStaging")
              (may :GLUE2ComputingEndpointJobDescription "GLUE2ComputingEndpointJobDescription")
              (may :GLUE2ComputingEndpointTotalJobs "GLUE2ComputingEndpointTotalJobs")
              (may :GLUE2ComputingEndpointRunningJobs "GLUE2ComputingEndpointRunningJobs")
              (may :GLUE2ComputingEndpointWaitingJobs "GLUE2ComputingEndpointWaitingJobs")
              (may :GLUE2ComputingEndpointStagingJobs "GLUE2ComputingEndpointStagingJobs")
              (may :GLUE2ComputingEndpointSuspendedJobs "GLUE2ComputingEndpointSuspendedJobs")
              (may :GLUE2ComputingEndpointPreLRMSWaitingJobs "GLUE2ComputingEndpointPreLRMSWaitingJobs")
              (may :GLUE2ComputingEndpointComputingServiceForeignKey "GLUE2ComputingEndpointComputingServiceForeignKey"))

(object-class :GLUE2ComputingShare "GLUE2ComputingShare"
              (must :GLUE2ComputingShareServingState "GLUE2ComputingShareServingState")
              (may :GLUE2ComputingShareMappingQueue "GLUE2ComputingShareMappingQueue")
              (may :GLUE2ComputingShareMaxWallTime "GLUE2ComputingShareMaxWallTime")
              (may :GLUE2ComputingShareMaxMultiSlotWallTime "GLUE2ComputingShareMaxMultiSlotWallTime")
              (may :GLUE2ComputingShareMinWallTime "GLUE2ComputingShareMinWallTime")
              (may :GLUE2ComputingShareDefaultWallTime "GLUE2ComputingShareDefaultWallTime")
              (may :GLUE2ComputingShareMaxCPUTime "GLUE2ComputingShareMaxCPUTime")
              (may :GLUE2ComputingShareMaxTotalCPUTime "GLUE2ComputingShareMaxTotalCPUTime")
              (may :GLUE2ComputingShareMinCPUTime "GLUE2ComputingShareMinCPUTime")
              (may :GLUE2ComputingShareDefaultCPUTime "GLUE2ComputingShareDefaultCPUTime")
              (may :GLUE2ComputingShareMaxTotalJobs "GLUE2ComputingShareMaxTotalJobs")
              (may :GLUE2ComputingShareMaxRunningJobs "GLUE2ComputingShareMaxRunningJobs")
              (may :GLUE2ComputingShareMaxWaitingJobs "GLUE2ComputingShareMaxWaitingJobs")
              (may :GLUE2ComputingShareMaxPreLRMSWaitingJobs "GLUE2ComputingShareMaxPreLRMSWaitingJobs")
              (may :GLUE2ComputingShareMaxUserRunningJobs "GLUE2ComputingShareMaxUserRunningJobs")
              (may :GLUE2ComputingShareMaxSlotsPerJob "GLUE2ComputingShareMaxSlotsPerJob")
              (may :GLUE2ComputingShareMaxStageInStreams "GLUE2ComputingShareMaxStageInStreams")
              (may :GLUE2ComputingShareMaxStageOutStreams "GLUE2ComputingShareMaxStageOutStreams")
              (may :GLUE2ComputingShareSchedulingPolicy "GLUE2ComputingShareSchedulingPolicy")
              (may :GLUE2ComputingShareMaxMainMemory "GLUE2ComputingShareMaxMainMemory")
              (may :GLUE2ComputingShareGuaranteedMainMemory "GLUE2ComputingShareGuaranteedMainMemory")
              (may :GLUE2ComputingShareMaxVirtualMemory "GLUE2ComputingShareMaxVirtualMemory")
              (may :GLUE2ComputingShareGuaranteedVirtualMemory "GLUE2ComputingShareGuaranteedVirtualMemory")
              (may :GLUE2ComputingShareMaxDiskSpace "GLUE2ComputingShareMaxDiskSpace")
              (may :GLUE2ComputingShareDefaultStorageService "GLUE2ComputingShareDefaultStorageService")
              (may :GLUE2ComputingSharePreemption "GLUE2ComputingSharePreemption")
              (may :GLUE2ComputingShareTotalJobs "GLUE2ComputingShareTotalJobs")
              (may :GLUE2ComputingShareRunningJobs "GLUE2ComputingShareRunningJobs")
              (may :GLUE2ComputingShareLocalRunningJobs "GLUE2ComputingShareLocalRunningJobs")
              (may :GLUE2ComputingShareWaitingJobs "GLUE2ComputingShareWaitingJobs")
              (may :GLUE2ComputingShareLocalWaitingJobs "GLUE2ComputingShareLocalWaitingJobs")
              (may :GLUE2ComputingShareSuspendedJobs "GLUE2ComputingShareSuspendedJobs")
              (may :GLUE2ComputingShareLocalSuspendedJobs "GLUE2ComputingShareLocalSuspendedJobs")
              (may :GLUE2ComputingShareStagingJobs "GLUE2ComputingShareStagingJobs")
              (may :GLUE2ComputingShareLocalStagingJobs "GLUE2ComputingShareLocalStagingJobs")
              (may :GLUE2ComputingSharePreLRMSWaitingJobs "GLUE2ComputingSharePreLRMSWaitingJobs")
              (may :GLUE2ComputingShareEstimatedAverageWaitingTime "GLUE2ComputingShareEstimatedAverageWaitingTime")
              (may :GLUE2ComputingShareEstimatedWorstWaitingTime "GLUE2ComputingShareEstimatedWorstWaitingTime")
              (may :GLUE2ComputingShareFreeSlots "GLUE2ComputingShareFreeSlots")
              (may :GLUE2ComputingShareFreeSlotsWithDuration "GLUE2ComputingShareFreeSlotsWithDuration")
              (may :GLUE2ComputingShareUsedSlots "GLUE2ComputingShareUsedSlots")
              (may :GLUE2ComputingShareRequestedSlots "GLUE2ComputingShareRequestedSlots")
              (may :GLUE2ComputingShareReservationPolicy "GLUE2ComputingShareReservationPolicy")
              (may :GLUE2ComputingShareTag "GLUE2ComputingShareTag")
              (may :GLUE2ComputingShareComputingEndpointForeignKey "GLUE2ComputingShareComputingEndpointForeignKey")
              (may :GLUE2ComputingShareExecutionEnvironmentForeignKey "GLUE2ComputingShareExecutionEnvironmentForeignKey")
              (may :GLUE2ComputingShareComputingServiceForeignKey "GLUE2ComputingShareComputingServiceForeignKey"))

(object-class :GLUE2ComputingManager "GLUE2ComputingManager"
              (may :GLUE2ComputingManagerReservation "GLUE2ComputingManagerReservation")
              (may :GLUE2ComputingManagerBulkSubmission "GLUE2ComputingManagerBulkSubmission")
              (may :GLUE2ComputingManagerTotalPhysicalCPUs "GLUE2ComputingManagerTotalPhysicalCPUs")
              (may :GLUE2ComputingManagerTotalLogicalCPUs "GLUE2ComputingManagerTotalLogicalCPUs")
              (may :GLUE2ComputingManagerTotalSlots "GLUE2ComputingManagerTotalSlots")
              (may :GLUE2ComputingManagerSlotsUsedByLocalJobs "GLUE2ComputingManagerSlotsUsedByLocalJobs")
              (may :GLUE2ComputingManagerSlotsUsedByGridJobs "GLUE2ComputingManagerSlotsUsedByGridJobs")
              (may :GLUE2ComputingManagerHomogeneous "GLUE2ComputingManagerHomogeneous")
              (may :GLUE2ComputingManagerNetworkInfo "GLUE2ComputingManagerNetworkInfo")
              (may :GLUE2ComputingManagerLogicalCPUDistribution "GLUE2ComputingManagerLogicalCPUDistribution")
              (may :GLUE2ComputingManagerWorkingAreaShared "GLUE2ComputingManagerWorkingAreaShared")
              (may :GLUE2ComputingManagerWorkingAreaGuaranteed "GLUE2ComputingManagerWorkingAreaGuaranteed")
              (may :GLUE2ComputingManagerWorkingAreaTotal "GLUE2ComputingManagerWorkingAreaTotal")
              (may :GLUE2ComputingManagerWorkingAreaFree "GLUE2ComputingManagerWorkingAreaFree")
              (may :GLUE2ComputingManagerWorkingAreaLifeTime "GLUE2ComputingManagerWorkingAreaLifeTime")
              (may :GLUE2ComputingManagerWorkingAreaMultiSlotTotal "GLUE2ComputingManagerWorkingAreaMultiSlotTotal")
              (may :GLUE2ComputingManagerWorkingAreaMultiSlotFree "GLUE2ComputingManagerWorkingAreaMultiSlotFree")
              (may :GLUE2ComputingManagerWorkingAreaMultiSlotLifeTime "GLUE2ComputingManagerWorkingAreaMultiSlotLifeTime")
              (may :GLUE2ComputingManagerCacheTotal "GLUE2ComputingManagerCacheTotal")
              (may :GLUE2ComputingManagerCacheFree "GLUE2ComputingManagerCacheFree")
              (may :GLUE2ComputingManagerTmpDir "GLUE2ComputingManagerTmpDir")
              (may :GLUE2ComputingManagerScratchDir "GLUE2ComputingManagerScratchDir")
              (may :GLUE2ComputingManagerApplicationDir "GLUE2ComputingManagerApplicationDir")
              (may :GLUE2ComputingManagerComputingServiceForeignKey "GLUE2ComputingManagerComputingServiceForeignKey"))

(object-class :GLUE2Benchmark "GLUE2Benchmark"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2BenchmarkID "GLUE2BenchmarkID")
              (must :GLUE2BenchmarkType "GLUE2BenchmarkType")
              (must :GLUE2BenchmarkValue "GLUE2BenchmarkValue")
              (may :GLUE2BenchmarkExecutionEnvironmentForeignKey "GLUE2BenchmarkExecutionEnvironmentForeignKey")
              (may :GLUE2BenchmarkComputingManagerForeignKey "GLUE2BenchmarkComputingManagerForeignKey"))

(object-class :GLUE2ExecutionEnvironment "GLUE2ExecutionEnvironment"
              (must :GLUE2ExecutionEnvironmentPlatform "GLUE2ExecutionEnvironmentPlatform")
              (must :GLUE2ExecutionEnvironmentMainMemorySize "GLUE2ExecutionEnvironmentMainMemorySize")
              (must :GLUE2ExecutionEnvironmentOSFamily "GLUE2ExecutionEnvironmentOSFamily")
              (must :GLUE2ExecutionEnvironmentConnectivityIn "GLUE2ExecutionEnvironmentConnectivityIn")
              (must :GLUE2ExecutionEnvironmentConnectivityOut "GLUE2ExecutionEnvironmentConnectivityOut")
              (may :GLUE2ExecutionEnvironmentVirtualMachine "GLUE2ExecutionEnvironmentVirtualMachine")
              (may :GLUE2ExecutionEnvironmentTotalInstances "GLUE2ExecutionEnvironmentTotalInstances")
              (may :GLUE2ExecutionEnvironmentUsedInstances "GLUE2ExecutionEnvironmentUsedInstances")
              (may :GLUE2ExecutionEnvironmentUnavailableInstances "GLUE2ExecutionEnvironmentUnavailableInstances")
              (may :GLUE2ExecutionEnvironmentPhysicalCPUs "GLUE2ExecutionEnvironmentPhysicalCPUs")
              (may :GLUE2ExecutionEnvironmentLogicalCPUs "GLUE2ExecutionEnvironmentLogicalCPUs")
              (may :GLUE2ExecutionEnvironmentCPUMultiplicity "GLUE2ExecutionEnvironmentCPUMultiplicity")
              (may :GLUE2ExecutionEnvironmentCPUVendor "GLUE2ExecutionEnvironmentCPUVendor")
              (may :GLUE2ExecutionEnvironmentCPUModel "GLUE2ExecutionEnvironmentCPUModel")
              (may :GLUE2ExecutionEnvironmentCPUVersion "GLUE2ExecutionEnvironmentCPUVersion")
              (may :GLUE2ExecutionEnvironmentCPUClockSpeed "GLUE2ExecutionEnvironmentCPUClockSpeed")
              (may :GLUE2ExecutionEnvironmentCPUTimeScalingFactor "GLUE2ExecutionEnvironmentCPUTimeScalingFactor")
              (may :GLUE2ExecutionEnvironmentWallTimeScalingFactor "GLUE2ExecutionEnvironmentWallTimeScalingFactor")
              (may :GLUE2ExecutionEnvironmentVirtualMemorySize "GLUE2ExecutionEnvironmentVirtualMemorySize")
              (may :GLUE2ExecutionEnvironmentOSName "GLUE2ExecutionEnvironmentOSName")
              (may :GLUE2ExecutionEnvironmentOSVersion "GLUE2ExecutionEnvironmentOSVersion")
              (may :GLUE2ExecutionEnvironmentNetworkInfo "GLUE2ExecutionEnvironmentNetworkInfo")
              (may :GLUE2ExecutionEnvironmentComputingManagerForeignKey "GLUE2ExecutionEnvironmentComputingManagerForeignKey"))

(object-class :GLUE2ApplicationEnvironment "GLUE2ApplicationEnvironment"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ApplicationEnvironmentID "GLUE2ApplicationEnvironmentID")
              (must :GLUE2ApplicationEnvironmentAppName "GLUE2ApplicationEnvironmentAppName")
              (must :GLUE2ApplicationEnvironmentComputingManagerForeignKey "GLUE2ApplicationEnvironmentComputingManagerForeignKey")
              (may :GLUE2ApplicationEnvironmentAppVersion "GLUE2ApplicationEnvironmentAppVersion")
              (may :GLUE2ApplicationEnvironmentRepository "GLUE2ApplicationEnvironmentRepository")
              (may :GLUE2ApplicationEnvironmentState "GLUE2ApplicationEnvironmentState")
              (may :GLUE2ApplicationEnvironmentRemovalDate "GLUE2ApplicationEnvironmentRemovalDate")
              (may :GLUE2ApplicationEnvironmentLicense "GLUE2ApplicationEnvironmentLicense")
              (may :GLUE2ApplicationEnvironmentDescription "GLUE2ApplicationEnvironmentDescription")
              (may :GLUE2ApplicationEnvironmentBestBenchmark "GLUE2ApplicationEnvironmentBestBenchmark")
              (may :GLUE2ApplicationEnvironmentParallelSupport "GLUE2ApplicationEnvironmentParallelSupport")
              (may :GLUE2ApplicationEnvironmentMaxSlots "GLUE2ApplicationEnvironmentMaxSlots")
              (may :GLUE2ApplicationEnvironmentMaxJobs "GLUE2ApplicationEnvironmentMaxJobs")
              (may :GLUE2ApplicationEnvironmentMaxUserSeats "GLUE2ApplicationEnvironmentMaxUserSeats")
              (may :GLUE2ApplicationEnvironmentFreeSlots "GLUE2ApplicationEnvironmentFreeSlots")
              (may :GLUE2ApplicationEnvironmentFreeJobs "GLUE2ApplicationEnvironmentFreeJobs")
              (may :GLUE2ApplicationEnvironmentFreeUserSeats "GLUE2ApplicationEnvironmentFreeUserSeats")
              (may :GLUE2ApplicationEnvironmentExecutionEnvironmentForeignKey "GLUE2ApplicationEnvironmentExecutionEnvironmentForeignKey"))

(object-class :GLUE2ApplicationHandle "GLUE2ApplicationHandle"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ApplicationHandleID "GLUE2ApplicationHandleID")
              (must :GLUE2ApplicationHandleType "GLUE2ApplicationHandleType")
              (must :GLUE2ApplicationHandleValue "GLUE2ApplicationHandleValue")
              (must :GLUE2ApplicationHandleApplicationEnvironmentForeignKey "GLUE2ApplicationHandleApplicationEnvironmentForeignKey"))

(object-class :GLUE2ComputingActivity "GLUE2ComputingActivity"
              (must :GLUE2ComputingActivityState "GLUE2ComputingActivityState")
              (must :GLUE2ComputingActivityOwner "GLUE2ComputingActivityOwner")
              (may :GLUE2ComputingActivityType "GLUE2ComputingActivityType")
              (may :GLUE2ComputingActivityIDFromEndpoint "GLUE2ComputingActivityIDFromEndpoint")
              (may :GLUE2ComputingActivityLocalIDFromManager "GLUE2ComputingActivityLocalIDFromManager")
              (may :GLUE2ComputingActivityJobDescription "GLUE2ComputingActivityJobDescription")
              (may :GLUE2ComputingActivityRestartState "GLUE2ComputingActivityRestartState")
              (may :GLUE2ComputingActivityExitCode "GLUE2ComputingActivityExitCode")
              (may :GLUE2ComputingActivityComputingManagerExitCode "GLUE2ComputingActivityComputingManagerExitCode")
              (may :GLUE2ComputingActivityError "GLUE2ComputingActivityError")
              (may :GLUE2ComputingActivityWaitingPosition "GLUE2ComputingActivityWaitingPosition")
              (may :GLUE2ComputingActivityUserDomain "GLUE2ComputingActivityUserDomain")
              (may :GLUE2ComputingActivityLocalOwner "GLUE2ComputingActivityLocalOwner")
              (may :GLUE2ComputingActivityRequestedTotalWallTime "GLUE2ComputingActivityRequestedTotalWallTime")
              (may :GLUE2ComputingActivityRequestedTotalCPUTime "GLUE2ComputingActivityRequestedTotalCPUTime")
              (may :GLUE2ComputingActivityRequestedSlots "GLUE2ComputingActivityRequestedSlots")
              (may :GLUE2ComputingActivityRequestedApplicationEnvironment "GLUE2ComputingActivityRequestedApplicationEnvironment")
              (may :GLUE2ComputingActivityStdIn "GLUE2ComputingActivityStdIn")
              (may :GLUE2ComputingActivityStdOut "GLUE2ComputingActivityStdOut")
              (may :GLUE2ComputingActivityStdErr "GLUE2ComputingActivityStdErr")
              (may :GLUE2ComputingActivityLogDir "GLUE2ComputingActivityLogDir")
              (may :GLUE2ComputingActivityExecutionNode "GLUE2ComputingActivityExecutionNode")
              (may :GLUE2ComputingActivityQueue "GLUE2ComputingActivityQueue")
              (may :GLUE2ComputingActivityUsedTotalWallTime "GLUE2ComputingActivityUsedTotalWallTime")
              (may :GLUE2ComputingActivityUsedTotalCPUTime "GLUE2ComputingActivityUsedTotalCPUTime")
              (may :GLUE2ComputingActivityUsedMainMemory "GLUE2ComputingActivityUsedMainMemory")
              (may :GLUE2ComputingActivitySubmissionTime "GLUE2ComputingActivitySubmissionTime")
              (may :GLUE2ComputingActivityComputingManagerSubmissionTime "GLUE2ComputingActivityComputingManagerSubmissionTime")
              (may :GLUE2ComputingActivityStartTime "GLUE2ComputingActivityStartTime")
              (may :GLUE2ComputingActivityComputingManagerEndTime "GLUE2ComputingActivityComputingManagerEndTime")
              (may :GLUE2ComputingActivityEndTime "GLUE2ComputingActivityEndTime")
              (may :GLUE2ComputingActivityWorkingAreaEraseTime "GLUE2ComputingActivityWorkingAreaEraseTime")
              (may :GLUE2ComputingActivityProxyExpirationTime "GLUE2ComputingActivityProxyExpirationTime")
              (may :GLUE2ComputingActivitySubmissionHost "GLUE2ComputingActivitySubmissionHost")
              (may :GLUE2ComputingActivitySubmissionClientName "GLUE2ComputingActivitySubmissionClientName")
              (may :GLUE2ComputingActivityOtherMessages "GLUE2ComputingActivityOtherMessages")
              (may :GLUE2ComputingActivityComputingEndpointForeignKey "GLUE2ComputingActivityComputingEndpointForeignKey")
              (may :GLUE2ComputingActivityComputingShareForeignKey "GLUE2ComputingActivityComputingShareForeignKey")
              (may :GLUE2ComputingActivityExecutionEnvironmentForeignKey "GLUE2ComputingActivityExecutionEnvironmentForeignKey"))

(object-class :GLUE2ToStorageService "GLUE2ToStorageService"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ToStorageServiceID "GLUE2ToStorageServiceID")
              (must :GLUE2ToStorageServiceLocalPath "GLUE2ToStorageServiceLocalPath")
              (must :GLUE2ToStorageServiceRemotePath "GLUE2ToStorageServiceRemotePath")
              (must :GLUE2ToStorageServiceComputingServiceForeignKey "GLUE2ToStorageServiceComputingServiceForeignKey")
              (must :GLUE2ToStorageServiceStorageServiceForeignKey "GLUE2ToStorageServiceStorageServiceForeignKey"))

(object-class :GLUE2StorageService "GLUE2StorageService")

(object-class :GLUE2StorageServiceCapacity "GLUE2StorageServiceCapacity"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2StorageServiceCapacityID "GLUE2StorageServiceCapacityID")
              (must :GLUE2StorageServiceCapacityType "GLUE2StorageServiceCapacityType")
              (must :GLUE2StorageServiceCapacityStorageServiceForeignKey "GLUE2StorageServiceCapacityStorageServiceForeignKey")
              (may :GLUE2StorageServiceCapacityTotalSize "GLUE2StorageServiceCapacityTotalSize")
              (may :GLUE2StorageServiceCapacityFreeSize "GLUE2StorageServiceCapacityFreeSize")
              (may :GLUE2StorageServiceCapacityUsedSize "GLUE2StorageServiceCapacityUsedSize")
              (may :GLUE2StorageServiceCapacityReservedSize "GLUE2StorageServiceCapacityReservedSize"))

(object-class :GLUE2StorageAccessProtocol "GLUE2StorageAccessProtocol"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2StorageAccessProtocolID "GLUE2StorageAccessProtocolID")
              (must :GLUE2StorageAccessProtocolType "GLUE2StorageAccessProtocolType")
              (must :GLUE2StorageAccessProtocolVersion "GLUE2StorageAccessProtocolVersion")
              (must :GLUE2StorageAccessProtocolStorageServiceForeignKey "GLUE2StorageAccessProtocolStorageServiceForeignKey")
              (may :GLUE2StorageAccessProtocolMaxStreams "GLUE2StorageAccessProtocolMaxStreams"))

(object-class :GLUE2StorageEndpoint "GLUE2StorageEndpoint"
              (may :GLUE2StorageEndpointStorageServiceForeignKey "GLUE2StorageEndpointStorageServiceForeignKey"))

(object-class :GLUE2StorageShare "GLUE2StorageShare"
              (must :GLUE2StorageShareServingState "GLUE2StorageShareServingState")
              (must :GLUE2StorageShareSharingID "GLUE2StorageShareSharingID")
              (must :GLUE2StorageShareAccessLatency "GLUE2StorageShareAccessLatency")
              (may :GLUE2StorageSharePath "GLUE2StorageSharePath")
              (may :GLUE2StorageShareAccessMode "GLUE2StorageShareAccessMode")
              (may :GLUE2StorageShareRetentionPolicy "GLUE2StorageShareRetentionPolicy")
              (may :GLUE2StorageShareExpirationMode "GLUE2StorageShareExpirationMode")
              (may :GLUE2StorageShareDefaultLifeTime "GLUE2StorageShareDefaultLifeTime")
              (may :GLUE2StorageShareMaximumLifeTime "GLUE2StorageShareMaximumLifeTime")
              (may :GLUE2StorageShareTag "GLUE2StorageShareTag")
              (may :GLUE2StorageShareStorageEndpointForeignKey "GLUE2StorageShareStorageEndpointForeignKey")
              (may :GLUE2StorageShareDataStoreForeignKey "GLUE2StorageShareDataStoreForeignKey")
              (may :GLUE2StorageShareStorageServiceForeignKey "GLUE2StorageShareStorageServiceForeignKey"))

(object-class :GLUE2StorageShareCapacity "GLUE2StorageShareCapacity"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2StorageShareCapacityID "GLUE2StorageShareCapacityID")
              (must :GLUE2StorageShareCapacityType "GLUE2StorageShareCapacityType")
              (must :GLUE2StorageShareCapacityStorageShareForeignKey "GLUE2StorageShareCapacityStorageShareForeignKey")
              (may :GLUE2StorageShareCapacityTotalSize "GLUE2StorageShareCapacityTotalSize")
              (may :GLUE2StorageShareCapacityFreeSize "GLUE2StorageShareCapacityFreeSize")
              (may :GLUE2StorageShareCapacityUsedSize "GLUE2StorageShareCapacityUsedSize")
              (may :GLUE2StorageShareCapacityReservedSize "GLUE2StorageShareCapacityReservedSize"))

(object-class :GLUE2StorageManager "GLUE2StorageManager"
              (may :GLUE2StorageManagerStorageServiceForeignKey "GLUE2StorageManagerStorageServiceForeignKey"))

(object-class :GLUE2DataStore "GLUE2DataStore"
              (must :GLUE2DataStoreType "GLUE2DataStoreType")
              (must :GLUE2DataStoreLatency "GLUE2DataStoreLatency")
              (may :GLUE2DataStoreTotalSize "GLUE2DataStoreTotalSize")
              (may :GLUE2DataStoreFreeSize "GLUE2DataStoreFreeSize")
              (may :GLUE2DataStoreUsedSize "GLUE2DataStoreUsedSize")
              (may :GLUE2DataStoreStorageManagerForeignKey "GLUE2DataStoreStorageManagerForeignKey"))

(object-class :GLUE2ToComputingService "GLUE2ToComputingService"
              (superclass :GLUE2Entity)
              (structural)
              (must :GLUE2ToComputingServiceID "GLUE2ToComputingServiceID")
              (must :GLUE2ToComputingServiceComputingServiceForeignKey "GLUE2ToComputingServiceComputingServiceForeignKey")
              (must :GLUE2ToComputingServiceStorageServiceForeignKey "GLUE2ToComputingServiceStorageServiceForeignKey")
              (may :GLUE2ToComputingServiceNetworkInfo "GLUE2ToComputingServiceNetworkInfo")
              (may :GLUE2ToComputingServiceBandwidth "GLUE2ToComputingServiceBandwidth")
              (may :GLUE2ToComputingServiceStorageAccessProtocolForeignKey "GLUE2ToComputingServiceStorageAccessProtocolForeignKey"))