(database :ldap
          (default-host "127.0.0.1")
          (default-port "389")
          (default-dn "cn=admin,Mds-Vo-name=local,o=grid")
          (default-password "alamakota"))

(object-class :qualityLabelledData "qualityLabelledData"
              (superclass :top)
              (may :subtreeMinimumQuality "subtreeMinimumQuality")
              (may :subtreeMaximumQuality "subtreeMaximumQuality"))

(object-class :GlueService "GlueService"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueServiceUniqueID "GlueServiceUniqueID")
              (may :GlueServiceVersion "GlueServiceVersion")
              (may :GlueServiceName "GlueServiceName")
              (may :GlueServiceType "GlueServiceType")
              (may :GlueServiceEndpoint "GlueServiceEndpoint")
              (may :GlueServiceStatus "GlueServiceStatus")
              (may :GlueServiceStatusInfo "GlueServiceStatusInfo")
              (may :GlueServiceWSDL "GlueServiceWSDL")
              (may :GlueServiceSemantics "GlueServiceSemantics")
              (may :GlueServiceStartTime "GlueServiceStartTime")
              (may :GlueServiceOwner "GlueServiceOwner")
              (may :GlueServiceAccessPointURL "GlueServiceAccessPointURL")
              (may :GlueServicePrimaryOwnerName "GlueServicePrimaryOwnerName")
              (may :GlueServicePrimaryOwnerContact "GlueServicePrimaryOwnerContact")
              (may :GlueServiceHostingOrganization "GlueServiceHostingOrganization")
              (may :GlueServiceMajorVersion "GlueServiceMajorVersion")
              (may :GlueServiceMinorVersion "GlueServiceMinorVersion")
              (may :GlueServicePatchVersion "GlueServicePatchVersion")
              (may :GlueServiceInformationServiceURL "GlueServiceInformationServiceURL")
              (may :GlueServiceAccessControlRule "GlueServiceAccessControlRule")
              (may :GlueServiceURI "GlueServiceURI")
              (may :GlueServiceAccessControlBaseRule "GlueServiceAccessControlBaseRule")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor")
              (may :GlueInformationServiceURL "GlueInformationServiceURL")
              (may :GlueForeignKey "GlueForeignKey"))

(object-class :GlueTop "GlueTop"
              (superclass :Top))

(object-class :certificationAuthority-V2 "certificationAuthority-V2"
              (superclass :certificationAuthority)
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :GlueHostBenchmark "GlueHostBenchmark"
              (superclass :GlueClusterTop)
              (may :GlueHostBenchmarkSI00 "GlueHostBenchmarkSI00")
              (may :GlueHostBenchmarkSF00 "GlueHostBenchmarkSF00"))

(object-class :userSecurityInformation "userSecurityInformation"
              (superclass :top)
              (may :supportedAlgorithms "supportedAlgorithms"))

(object-class :groupOfUniqueNames "groupOfUniqueNames"
              (superclass :top)
              (structural)
              (must :uniqueMember "uniqueMember")
              (must :cn "cn")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :description "description"))

(object-class :GlueSLArchitecture "GlueSLArchitecture"
              (superclass :GlueSLTop)
              (may :GlueSLArchitectureType "GlueSLArchitectureType"))

(object-class :subschema "subschema"
              (may :objectClasses "objectClasses")
              (may :attributeTypes "attributeTypes")
              (may :matchingRules "matchingRules")
              (may :matchingRuleUse "matchingRuleUse"))

(object-class :organizationalUnit "organizationalUnit"
              (superclass :top)
              (structural)
              (must :ou "ou")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :GlueGeneralTop "GlueGeneralTop"
              (superclass :GlueTop))

(object-class :GlueSchemaVersion "GlueSchemaVersion"
              (superclass :GlueGeneralTop)
              (must :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (must :GlueSchemaVersionMinor "GlueSchemaVersionMinor"))

(object-class :GlueSLPerformance "GlueSLPerformance"
              (superclass :GlueSLTop)
              (may :GlueSLPerformanceMaxIOCapacity "GlueSLPerformanceMaxIOCapacity"))

(object-class :olcDatabaseConfig "olcDatabaseConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcDatabase "olcDatabase")
              (may :olcHidden "olcHidden")
              (may :olcSuffix "olcSuffix")
              (may :olcSubordinate "olcSubordinate")
              (may :olcAccess "olcAccess")
              (may :olcAddContentAcl "olcAddContentAcl")
              (may :olcLastMod "olcLastMod")
              (may :olcLimits "olcLimits")
              (may :olcMaxDerefDepth "olcMaxDerefDepth")
              (may :olcPlugin "olcPlugin")
              (may :olcReadOnly "olcReadOnly")
              (may :olcReplica "olcReplica")
              (may :olcReplicaArgsFile "olcReplicaArgsFile")
              (may :olcReplicaPidFile "olcReplicaPidFile")
              (may :olcReplicationInterval "olcReplicationInterval")
              (may :olcReplogFile "olcReplogFile")
              (may :olcRequires "olcRequires")
              (may :olcRestrict "olcRestrict")
              (may :olcRootDN "olcRootDN")
              (may :olcRootPW "olcRootPW")
              (may :olcSchemaDN "olcSchemaDN")
              (may :olcSecurity "olcSecurity")
              (may :olcSizeLimit "olcSizeLimit")
              (may :olcSyncUseSubentry "olcSyncUseSubentry")
              (may :olcSyncrepl "olcSyncrepl")
              (may :olcTimeLimit "olcTimeLimit")
              (may :olcUpdateDN "olcUpdateDN")
              (may :olcUpdateRef "olcUpdateRef")
              (may :olcMirrorMode "olcMirrorMode")
              (may :olcMonitoring "olcMonitoring")
              (may :olcExtraAttrs "olcExtraAttrs"))

(object-class :locality "locality"
              (superclass :top)
              (structural)
              (may :street "street")
              (may :seeAlso "seeAlso")
              (may :searchGuide "searchGuide")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :OpenLDAProotDSE "OpenLDAProotDSE"
              (superclass :top)
              (structural)
              (may :cn "cn"))

(object-class :GlueSEAccessProtocol "GlueSEAccessProtocol"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEAccessProtocolLocalID "GlueSEAccessProtocolLocalID")
              (may :GlueSEAccessProtocolPort "GlueSEAccessProtocolPort")
              (may :GlueSEAccessProtocolVersion "GlueSEAccessProtocolVersion")
              (may :GlueSEAccessProtocolSupportedSecurity "GlueSEAccessProtocolSupportedSecurity")
              (may :GlueSEAccessProtocolAccessTime "GlueSEAccessProtocolAccessTime")
              (may :GlueSEAccessProtocolEndpoint "GlueSEAccessProtocolEndpoint")
              (may :GlueSEAccessProtocolCapability "GlueSEAccessProtocolCapability")
              (may :GlueSEAccessProtocolType "GlueSEAccessProtocolType")
              (may :GlueSEAccessProtocolMaxStreams "GlueSEAccessProtocolMaxStreams")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueSA "GlueSA"
              (superclass :GlueSATop)
              (structural)
              (must :GlueSALocalID "GlueSALocalID")
              (may :GlueSARoot "GlueSARoot")
              (may :GlueSAPath "GlueSAPath")
              (may :GlueSAType "GlueSAType")
              (may :GlueSAUniqueID "GlueSAUniqueID")
              (may :GlueSAName "GlueSAName")
              (may :GlueSATotalOnlineSize "GlueSATotalOnlineSize")
              (may :GlueSAFreeOnlineSize "GlueSAFreeOnlineSize")
              (may :GlueSAUsedOnlineSize "GlueSAUsedOnlineSize")
              (may :GlueSAReservedOnlineSize "GlueSAReservedOnlineSize")
              (may :GlueSATotalNearlineSize "GlueSATotalNearlineSize")
              (may :GlueSAFreeNearlineSize "GlueSAFreeNearlineSize")
              (may :GlueSAUsedNearlineSize "GlueSAUsedNearlineSize")
              (may :GlueSAReservedNearlineSize "GlueSAReservedNearlineSize")
              (may :GlueSARetentionPolicy "GlueSARetentionPolicy")
              (may :GlueSAAccessLatency "GlueSAAccessLatency")
              (may :GlueSAExpirationMode "GlueSAExpirationMode")
              (may :GlueSACapability "GlueSACapability")
              (may :GlueSAStateAvailableSpace "GlueSAStateAvailableSpace")
              (may :GlueSAStateUsedSpace "GlueSAStateUsedSpace")
              (may :GlueSAAccessControlBaseRule "GlueSAAccessControlBaseRule")
              (may :GlueChunkKey "GlueChunkKey")
              (may :GlueSAPolicyMaxFileSize "GlueSAPolicyMaxFileSize")
              (may :GlueSAPolicyMinFileSize "GlueSAPolicyMinFileSize")
              (may :GlueSAPolicyMaxData "GlueSAPolicyMaxData")
              (may :GlueSAPolicyMaxNumFiles "GlueSAPolicyMaxNumFiles")
              (may :GlueSAPolicyMaxPinDuration "GlueSAPolicyMaxPinDuration")
              (may :GlueSAPolicyQuota "GlueSAPolicyQuota")
              (may :GlueSAPolicyFileLifeTime "GlueSAPolicyFileLifeTime"))

(object-class :domain "domain"
              (superclass :top)
              (structural)
              (may :associatedName "associatedName")
              (may :description "description")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :searchGuide "searchGuide")
              (may :userPassword "userPassword")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :postalAddress "postalAddress")
              (may :postalCode "postalCode")
              (may :postOfficeBox "postOfficeBox")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :telephoneNumber "telephoneNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telexNumber "telexNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :destinationIndicator "destinationIndicator")
              (may :registeredAddress "registeredAddress")
              (may :x121Address "x121Address"))

(object-class :inetOrgPerson "inetOrgPerson"
              (superclass :organizationalPerson)
              (structural)
              (may :audio "audio")
              (may :businessCategory "businessCategory")
              (may :carLicense "carLicense")
              (may :departmentNumber "departmentNumber")
              (may :displayName "displayName")
              (may :employeeNumber "employeeNumber")
              (may :employeeType "employeeType")
              (may :givenName "givenName")
              (may :homePhone "homePhone")
              (may :homePostalAddress "homePostalAddress")
              (may :initials "initials")
              (may :jpegPhoto "jpegPhoto")
              (may :labeledURI "labeledURI")
              (may :mail "mail")
              (may :manager "manager")
              (may :mobile "mobile")
              (may :o "o")
              (may :pager "pager")
              (may :photo "photo")
              (may :roomNumber "roomNumber")
              (may :secretary "secretary")
              (may :uid "uid")
              (may :userCertificate "userCertificate")
              (may :preferredLanguage "preferredLanguage")
              (may :userSMIMECertificate "userSMIMECertificate")
              (may :userPKCS12 "userPKCS12"))

(object-class :GlueCluster "GlueCluster"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueClusterUniqueID "GlueClusterUniqueID")
              (may :GlueClusterName "GlueClusterName")
              (may :GlueClusterService "GlueClusterService")
              (may :GlueCEUniqueID "GlueCEUniqueID")
              (may :GlueClusterTmpDir "GlueClusterTmpDir")
              (may :GlueClusterWNTmpDir "GlueClusterWNTmpDir")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueCEInfo "GlueCEInfo"
              (superclass :GlueCETop)
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEInfoLRMSType "GlueCEInfoLRMSType")
              (may :GlueCEInfoLRMSVersion "GlueCEInfoLRMSVersion")
              (may :GlueCEInfoGRAMVersion "GlueCEInfoGRAMVersion")
              (may :GlueCEInfoHostName "GlueCEInfoHostName")
              (may :GlueCEInfoGatekeeperPort "GlueCEInfoGatekeeperPort")
              (may :GlueCEInfoContactString "GlueCEInfoContactString")
              (may :GlueCEInfoJobManager "GlueCEInfoJobManager")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE"))

(object-class :deltaCRL "deltaCRL"
              (superclass :top)
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :GlueSoftwareData "GlueSoftwareData"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSoftwareDataKey "GlueSoftwareDataKey")
              (may :GlueSoftwareDataValue "GlueSoftwareDataValue"))

(object-class :domainRelatedObject "domainRelatedObject"
              (superclass :top)
              (must :associatedDomain "associatedDomain"))

(object-class :GlueCESEBind "GlueCESEBind"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueCESEBindCEUniqueID "GlueCESEBindCEUniqueID")
              (must :GlueCESEBindSEUniqueID "GlueCESEBindSEUniqueID")
              (may :GlueCESEBindCEAccesspoint "GlueCESEBindCEAccesspoint")
              (may :GlueCESEBindMountInfo "GlueCESEBindMountInfo")
              (may :GlueCESEBindWeight "GlueCESEBindWeight"))

(object-class :GlueCEJob "GlueCEJob"
              (superclass :GlueCETop)
              (structural)
              (must :GlueCEJobGlobalID "GlueCEJobGlobalID")
              (may :GlueCEJobLocalOwner "GlueCEJobLocalOwner")
              (may :GlueCEJobGlobalOwner "GlueCEJobGlobalOwner")
              (may :GlueCEJobStatus "GlueCEJobStatus")
              (may :GlueCEJobSchedulerSpecific "GlueCEJobSchedulerSpecific")
              (may :GlueCEJobLocalID "GlueCEJobLocalID"))

(object-class :GlueSAAccessControlBase "GlueSAAccessControlBase"
              (superclass :GlueSATop)
              (may :GlueSAAccessControlBaseRule "GlueSAAccessControlBaseRule"))

(object-class :GlueSLTop "GlueSLTop"
              (superclass :GlueTop))

(object-class :GlueSE "GlueSE"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEUniqueID "GlueSEUniqueID")
              (may :GlueSEName "GlueSEName")
              (may :GlueSEPort "GlueSEPort")
              (may :GlueSEHostingSL "GlueSEHostingSL")
              (may :GlueSESizeTotal "GlueSESizeTotal")
              (may :GlueSESizeFree "GlueSESizeFree")
              (may :GlueSEArchitecture "GlueSEArchitecture")
              (may :GlueSEType "GlueSEType")
              (may :GlueSEImplementationName "GlueSEImplementationName")
              (may :GlueSEImplementationVersion "GlueSEImplementationVersion")
              (may :GlueSEStatus "GlueSEStatus")
              (may :GlueSETotalOnlineSize "GlueSETotalOnlineSize")
              (may :GlueSETotalNearlineSize "GlueSETotalNearlineSize")
              (may :GlueSEUsedOnlineSize "GlueSEUsedOnlineSize")
              (may :GlueSEUsedNearlineSize "GlueSEUsedNearlineSize")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor")
              (may :GlueSEStateCurrentIOLoad "GlueSEStateCurrentIOLoad")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :olcConfig "olcConfig"
              (superclass :top))

(object-class :GlueSLLocalFileSystem "GlueSLLocalFileSystem"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLLocalFileSystemName "GlueSLLocalFileSystemName")
              (may :GlueSLLocalFileSystemRoot "GlueSLLocalFileSystemRoot")
              (may :GlueSLLocalFileSystemSize "GlueSLLocalFileSystemSize")
              (may :GlueSLLocalFileSystemAvailableSpace "GlueSLLocalFileSystemAvailableSpace")
              (may :GlueSLLocalFileSystemReadOnly "GlueSLLocalFileSystemReadOnly")
              (may :GlueSLLocalFileSystemType "GlueSLLocalFileSystemType")
              (may :GlueSLLocalFileSystemClient "GlueSLLocalFileSystemClient"))

(object-class :olcGlobal "olcGlobal"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcConfigFile "olcConfigFile")
              (may :olcConfigDir "olcConfigDir")
              (may :olcAllows "olcAllows")
              (may :olcArgsFile "olcArgsFile")
              (may :olcAttributeOptions "olcAttributeOptions")
              (may :olcAuthIDRewrite "olcAuthIDRewrite")
              (may :olcAuthzPolicy "olcAuthzPolicy")
              (may :olcAuthzRegexp "olcAuthzRegexp")
              (may :olcConcurrency "olcConcurrency")
              (may :olcConnMaxPending "olcConnMaxPending")
              (may :olcConnMaxPendingAuth "olcConnMaxPendingAuth")
              (may :olcDisallows "olcDisallows")
              (may :olcGentleHUP "olcGentleHUP")
              (may :olcIdleTimeout "olcIdleTimeout")
              (may :olcIndexSubstrIfMaxLen "olcIndexSubstrIfMaxLen")
              (may :olcIndexSubstrIfMinLen "olcIndexSubstrIfMinLen")
              (may :olcIndexSubstrAnyLen "olcIndexSubstrAnyLen")
              (may :olcIndexSubstrAnyStep "olcIndexSubstrAnyStep")
              (may :olcIndexIntLen "olcIndexIntLen")
              (may :olcLocalSSF "olcLocalSSF")
              (may :olcLogFile "olcLogFile")
              (may :olcLogLevel "olcLogLevel")
              (may :olcPasswordCryptSaltFormat "olcPasswordCryptSaltFormat")
              (may :olcPasswordHash "olcPasswordHash")
              (may :olcPidFile "olcPidFile")
              (may :olcPluginLogFile "olcPluginLogFile")
              (may :olcReadOnly "olcReadOnly")
              (may :olcReferral "olcReferral")
              (may :olcReplogFile "olcReplogFile")
              (may :olcRequires "olcRequires")
              (may :olcRestrict "olcRestrict")
              (may :olcReverseLookup "olcReverseLookup")
              (may :olcRootDSE "olcRootDSE")
              (may :olcSaslAuxprops "olcSaslAuxprops")
              (may :olcSaslHost "olcSaslHost")
              (may :olcSaslRealm "olcSaslRealm")
              (may :olcSaslSecProps "olcSaslSecProps")
              (may :olcSecurity "olcSecurity")
              (may :olcServerID "olcServerID")
              (may :olcSizeLimit "olcSizeLimit")
              (may :olcSockbufMaxIncoming "olcSockbufMaxIncoming")
              (may :olcSockbufMaxIncomingAuth "olcSockbufMaxIncomingAuth")
              (may :olcTCPBuffer "olcTCPBuffer")
              (may :olcThreads "olcThreads")
              (may :olcTimeLimit "olcTimeLimit")
              (may :olcTLSCACertificateFile "olcTLSCACertificateFile")
              (may :olcTLSCACertificatePath "olcTLSCACertificatePath")
              (may :olcTLSCertificateFile "olcTLSCertificateFile")
              (may :olcTLSCertificateKeyFile "olcTLSCertificateKeyFile")
              (may :olcTLSCipherSuite "olcTLSCipherSuite")
              (may :olcTLSCRLCheck "olcTLSCRLCheck")
              (may :olcTLSRandFile "olcTLSRandFile")
              (may :olcTLSVerifyClient "olcTLSVerifyClient")
              (may :olcTLSDHParamFile "olcTLSDHParamFile")
              (may :olcTLSCRLFile "olcTLSCRLFile")
              (may :olcToolThreads "olcToolThreads")
              (may :olcWriteTimeout "olcWriteTimeout")
              (may :olcObjectIdentifier "olcObjectIdentifier")
              (may :olcAttributeTypes "olcAttributeTypes")
              (may :olcObjectClasses "olcObjectClasses")
              (may :olcDitContentRules "olcDitContentRules")
              (may :olcLdapSyntaxes "olcLdapSyntaxes"))

(object-class :GlueCEPolicy "GlueCEPolicy"
              (superclass :GlueCETop)
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption"))

(object-class :olcSchemaConfig "olcSchemaConfig"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcObjectIdentifier "olcObjectIdentifier")
              (may :olcLdapSyntaxes "olcLdapSyntaxes")
              (may :olcAttributeTypes "olcAttributeTypes")
              (may :olcObjectClasses "olcObjectClasses")
              (may :olcDitContentRules "olcDitContentRules"))

(object-class :certificationAuthority "certificationAuthority"
              (superclass :top)
              (must :authorityRevocationList "authorityRevocationList")
              (must :certificateRevocationList "certificateRevocationList")
              (must :cACertificate "cACertificate")
              (may :crossCertificatePair "crossCertificatePair"))

(object-class :GlueLocation "GlueLocation"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueLocationLocalID "GlueLocationLocalID")
              (may :GlueLocationName "GlueLocationName")
              (may :GlueLocationPath "GlueLocationPath")
              (may :GlueLocationVersion "GlueLocationVersion"))

(object-class :GlueSEState "GlueSEState"
              (superclass :GlueSETop)
              (may :GlueSEStateCurrentIOLoad "GlueSEStateCurrentIOLoad"))

(object-class :GlueSLFile "GlueSLFile"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLFileName "GlueSLFileName")
              (may :GlueSLFileSize "GlueSLFileSize")
              (may :GlueSLFileCreationDate "GlueSLFileCreationDate")
              (may :GlueSLFileLastModified "GlueSLFileLastModified")
              (may :GlueSLFileLastAccessed "GlueSLFileLastAccessed")
              (may :GlueSLFileLatency "GlueSLFileLatency")
              (may :GlueSLFileLifeTime "GlueSLFileLifeTime")
              (may :GlueSLFilePath "GlueSLFilePath"))

(object-class :GlueServiceData "GlueServiceData"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueServiceDataKey "GlueServiceDataKey")
              (may :GlueServiceDataValue "GlueServiceDataValue")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueKey "GlueKey"
              (superclass :GlueGeneralTop)
              (may :GlueChunkKey "GlueChunkKey")
              (may :GlueForeignKey "GlueForeignKey"))

(object-class :pilotOrganization "pilotOrganization"
              (superclass :organization)
              (structural)
              (may :buildingName "buildingName"))

(object-class :friendlyCountry "friendlyCountry"
              (superclass :country)
              (structural))

(object-class :pkiCA "pkiCA"
              (superclass :top)
              (may :authorityRevocationList "authorityRevocationList")
              (may :certificateRevocationList "certificateRevocationList")
              (may :cACertificate "cACertificate")
              (may :crossCertificatePair "crossCertificatePair"))

(object-class :olcOverlayConfig "olcOverlayConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcOverlay "olcOverlay"))

(object-class :pilotPerson "pilotPerson"
              (superclass :person)
              (structural)
              (may :textEncodedORAddress "textEncodedORAddress")
              (may :roomNumber "roomNumber")
              (may :userClass "userClass")
              (may :homePostalAddress "homePostalAddress")
              (may :secretary "secretary")
              (may :personalTitle "personalTitle")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :businessCategory "businessCategory")
              (may :janetMailbox "janetMailbox")
              (may :otherMailbox "otherMailbox")
              (may :organizationalStatus "organizationalStatus")
              (may :mailPreferenceOption "mailPreferenceOption")
              (may :personalSignature "personalSignature"))

(object-class :account "account"
              (superclass :top)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :host "host"))

(object-class :dNSDomain "dNSDomain"
              (superclass :domain)
              (structural))

(object-class :GlueSETop "GlueSETop"
              (superclass :GlueTop))

(object-class :GlueSEControlProtocol "GlueSEControlProtocol"
              (superclass :GlueSETop)
              (structural)
              (must :GlueSEControlProtocolLocalID "GlueSEControlProtocolLocalID")
              (may :GlueSEControlProtocolVersion "GlueSEControlProtocolVersion")
              (may :GlueSEControlProtocolEndpoint "GlueSEControlProtocolEndpoint")
              (may :GlueSEControlProtocolCapability "GlueSEControlProtocolCapability")
              (may :GlueSEControlProtocolType "GlueSEControlProtocolType")
              (may :GlueChunkKey "GlueChunkKey"))

(object-class :GlueSAState "GlueSAState"
              (superclass :GlueSATop)
              (may :GlueSAStateAvailableSpace "GlueSAStateAvailableSpace")
              (may :GlueSAStateUsedSpace "GlueSAStateUsedSpace"))

(object-class :GlueHostRemoteFileSystem "GlueHostRemoteFileSystem"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostRemoteFileSystemName "GlueHostRemoteFileSystemName")
              (may :GlueHostRemoteFileSystemRoot "GlueHostRemoteFileSystemRoot")
              (may :GlueHostRemoteFileSystemSize "GlueHostRemoteFileSystemSize")
              (may :GlueHostRemoteFileSystemAvailableSpace "GlueHostRemoteFileSystemAvailableSpace")
              (may :GlueHostRemoteFileSystemReadOnly "GlueHostRemoteFileSystemReadOnly")
              (may :GlueHostRemoteFileSystemType "GlueHostRemoteFileSystemType")
              (may :GlueHostRemoteFileSystemName "GlueHostRemoteFileSystemName")
              (may :GlueHostRemoteFileSystemServer "GlueHostRemoteFileSystemServer"))

(object-class :GlueSL "GlueSL"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLUniqueID "GlueSLUniqueID")
              (may :GlueSLName "GlueSLName")
              (may :GlueSLService "GlueSLService"))

(object-class :cRLDistributionPoint "cRLDistributionPoint"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :certificateRevocationList "certificateRevocationList")
              (may :authorityRevocationList "authorityRevocationList")
              (may :deltaRevocationList "deltaRevocationList"))

(object-class :uidObject "uidObject"
              (superclass :top)
              (must :uid "uid"))

(object-class :GlueSubCluster "GlueSubCluster"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSubClusterUniqueID "GlueSubClusterUniqueID")
              (may :GlueSubClusterName "GlueSubClusterName")
              (may :GlueSubClusterWNTmpDir "GlueSubClusterWNTmpDir")
              (may :GlueSubClusterTmpDir "GlueSubClusterTmpDir")
              (may :GlueSubClusterPhysicalCPUs "GlueSubClusterPhysicalCPUs")
              (may :GlueSubClusterLogicalCPUs "GlueSubClusterLogicalCPUs")
              (may :GlueHostOperatingSystemName "GlueHostOperatingSystemName")
              (may :GlueHostOperatingSystemRelease "GlueHostOperatingSystemRelease")
              (may :GlueHostOperatingSystemVersion "GlueHostOperatingSystemVersion")
              (may :GlueHostArchitecturePlatformType "GlueHostArchitecturePlatformType")
              (may :GlueHostArchitectureSMPSize "GlueHostArchitectureSMPSize")
              (may :GlueHostProcessorVendor "GlueHostProcessorVendor")
              (may :GlueHostProcessorModel "GlueHostProcessorModel")
              (may :GlueHostProcessorVersion "GlueHostProcessorVersion")
              (may :GlueHostProcessorClockSpeed "GlueHostProcessorClockSpeed")
              (may :GlueHostProcessorInstructionSet "GlueHostProcessorInstructionSet")
              (may :GlueHostProcessorOtherDescription "GlueHostProcessorOtherDescription")
              (may :GlueHostApplicationSoftwareRunTimeEnvironment "GlueHostApplicationSoftwareRunTimeEnvironment")
              (may :GlueHostBenchmarkSI00 "GlueHostBenchmarkSI00")
              (may :GlueHostBenchmarkSF00 "GlueHostBenchmarkSF00")
              (may :GlueHostNetworkAdapterOutboundIP "GlueHostNetworkAdapterOutboundIP")
              (may :GlueHostNetworkAdapterInboundIP "GlueHostNetworkAdapterInboundIP")
              (may :GlueHostMainMemoryRAMSize "GlueHostMainMemoryRAMSize")
              (may :GlueHostMainMemoryVirtualSize "GlueHostMainMemoryVirtualSize"))

(object-class :GlueClusterTop "GlueClusterTop"
              (superclass :GlueTop))

(object-class :alias "alias"
              (superclass :top)
              (structural)
              (must :aliasedObjectName "aliasedObjectName"))

(object-class :olcBackendConfig "olcBackendConfig"
              (superclass :olcConfig)
              (structural)
              (must :olcBackend "olcBackend"))

(object-class :GlueHostArchitecture "GlueHostArchitecture"
              (superclass :GlueClusterTop)
              (may :GlueHostArchitecturePlatformType "GlueHostArchitecturePlatformType")
              (may :GlueHostArchitectureSMPSize "GlueHostArchitectureSMPSize"))

(object-class :olcModuleList "olcModuleList"
              (superclass :olcConfig)
              (structural)
              (may :cn "cn")
              (may :olcModulePath "olcModulePath")
              (may :olcModuleLoad "olcModuleLoad"))

(object-class :simpleSecurityObject "simpleSecurityObject"
              (superclass :top)
              (must :userPassword "userPassword"))

(object-class :groupOfNames "groupOfNames"
              (superclass :top)
              (structural)
              (must :member "member")
              (must :cn "cn")
              (may :businessCategory "businessCategory")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :description "description"))

(object-class :dSA "dSA"
              (superclass :applicationEntity)
              (structural)
              (may :knowledgeInformation "knowledgeInformation"))

(object-class :subentry "subentry"
              (superclass :top)
              (structural)
              (must :cn "cn"))

(object-class :GlueSATop "GlueSATop"
              (superclass :GlueTop))

(object-class :documentSeries "documentSeries"
              (superclass :top)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso"))

(object-class :GlueCEAccessControlBase "GlueCEAccessControlBase"
              (superclass :GlueCETop)
              (must :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule"))

(object-class :organization "organization"
              (superclass :top)
              (structural)
              (must :o "o")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :applicationEntity "applicationEntity"
              (superclass :top)
              (structural)
              (must :presentationAddress "presentationAddress")
              (must :cn "cn")
              (may :supportedApplicationContext "supportedApplicationContext")
              (may :seeAlso "seeAlso")
              (may :ou "ou")
              (may :o "o")
              (may :l "l")
              (may :description "description"))

(object-class :organizationalPerson "organizationalPerson"
              (superclass :person)
              (structural)
              (may :title "title")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :ou "ou")
              (may :st "st")
              (may :l "l"))

(object-class :GlueHostOperatingSystem "GlueHostOperatingSystem"
              (superclass :GlueClusterTop)
              (may :GlueHostOperatingSystemName "GlueHostOperatingSystemName")
              (may :GlueHostOperatingSystemRelease "GlueHostOperatingSystemRelease")
              (may :GlueHostOperatingSystemVersion "GlueHostOperatingSystemVersion"))

(object-class :GlueVOView "GlueVOView"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueVOViewLocalID "GlueVOViewLocalID")
              (may :GlueCECapability "GlueCECapability")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE")
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeCPUs "GlueCEStateFreeCPUs")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots")
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption")
              (may :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule"))

(object-class :GlueHostStorageDevice "GlueHostStorageDevice"
              (superclass :GlueClusterTop)
              (must :GlueHostStorageDeviceName "GlueHostStorageDeviceName")
              (may :GlueHostStorageDeviceType "GlueHostStorageDeviceType")
              (may :GlueHostStorageDeviceTransferRate "GlueHostStorageDeviceTransferRate")
              (may :GlueHostStorageDeviceSize "GlueHostStorageDeviceSize")
              (may :GlueHostStorageDeviceAvailableSpace "GlueHostStorageDeviceAvailableSpace"))

(object-class :organizationalRole "organizationalRole"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :seeAlso "seeAlso")
              (may :roleOccupant "roleOccupant")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :ou "ou")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :top "top"
              (must :objectClass "objectClass"))

(object-class :GlueSAPolicy "GlueSAPolicy"
              (superclass :GlueSATop)
              (may :GlueSAPolicyMaxFileSize "GlueSAPolicyMaxFileSize")
              (may :GlueSAPolicyMinFileSize "GlueSAPolicyMinFileSize")
              (may :GlueSAPolicyMaxData "GlueSAPolicyMaxData")
              (may :GlueSAPolicyMaxNumFiles "GlueSAPolicyMaxNumFiles")
              (may :GlueSAPolicyMaxPinDuration "GlueSAPolicyMaxPinDuration")
              (may :GlueSAPolicyQuota "GlueSAPolicyQuota")
              (may :GlueSAPolicyFileLifeTime "GlueSAPolicyFileLifeTime"))

(object-class :RFC822localPart "RFC822localPart"
              (superclass :domain)
              (structural)
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :telephoneNumber "telephoneNumber")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :postalAddress "postalAddress")
              (may :postalCode "postalCode")
              (may :postOfficeBox "postOfficeBox")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :telephoneNumber "telephoneNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telexNumber "telexNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :destinationIndicator "destinationIndicator")
              (may :registeredAddress "registeredAddress")
              (may :x121Address "x121Address"))

(object-class :person "person"
              (superclass :top)
              (structural)
              (must :sn "sn")
              (must :cn "cn")
              (may :userPassword "userPassword")
              (may :telephoneNumber "telephoneNumber")
              (may :seeAlso "seeAlso")
              (may :description "description"))

(object-class :GlueHostProcessor "GlueHostProcessor"
              (superclass :GlueClusterTop)
              (may :GlueHostProcessorVendor "GlueHostProcessorVendor")
              (may :GlueHostProcessorModel "GlueHostProcessorModel")
              (may :GlueHostProcessorVersion "GlueHostProcessorVersion")
              (may :GlueHostProcessorClockSpeed "GlueHostProcessorClockSpeed")
              (may :GlueHostProcessorInstructionSet "GlueHostProcessorInstructionSet")
              (may :GlueHostProcessorOtherDescription "GlueHostProcessorOtherDescription")
              (may :GlueHostProcessorCacheL1 "GlueHostProcessorCacheL1")
              (may :GlueHostProcessorCacheL1I "GlueHostProcessorCacheL1I")
              (may :GlueHostProcessorCacheL1D "GlueHostProcessorCacheL1D")
              (may :GlueHostProcessorCacheL2 "GlueHostProcessorCacheL2"))

(object-class :device "device"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :serialNumber "serialNumber")
              (may :seeAlso "seeAlso")
              (may :owner "owner")
              (may :ou "ou")
              (may :o "o")
              (may :l "l")
              (may :description "description"))

(object-class :country "country"
              (superclass :top)
              (structural)
              (must :c "c")
              (may :searchGuide "searchGuide")
              (may :description "description"))

(object-class :GlueCE "GlueCE"
              (superclass :GlueCETop)
              (structural)
              (must :GlueCEUniqueID "GlueCEUniqueID")
              (may :GlueCEName "GlueCEName")
              (may :GlueCEHostingCluster "GlueCEHostingCluster")
              (may :GlueSiteUniqueID "GlueSiteUniqueID")
              (may :GlueCEImplementationName "GlueCEImplementationName")
              (may :GlueCEImplementationVersion "GlueCEImplementationVersion")
              (may :GlueCECapability "GlueCECapability")
              (may :GlueCEInfoTotalCPUs "GlueCEInfoTotalCPUs")
              (may :GlueCEInfoLRMSType "GlueCEInfoLRMSType")
              (may :GlueCEInfoLRMSVersion "GlueCEInfoLRMSVersion")
              (may :GlueCEInfoGRAMVersion "GlueCEInfoGRAMVersion")
              (may :GlueCEInfoHostName "GlueCEInfoHostName")
              (may :GlueCEInfoGatekeeperPort "GlueCEInfoGatekeeperPort")
              (may :GlueCEInfoContactString "GlueCEInfoContactString")
              (may :GlueCEInfoJobManager "GlueCEInfoJobManager")
              (may :GlueCEInfoApplicationDir "GlueCEInfoApplicationDir")
              (may :GlueCEInfoDataDir "GlueCEInfoDataDir")
              (may :GlueCEInfoDefaultSE "GlueCEInfoDefaultSE")
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots")
              (may :GlueCEPolicyPriority "GlueCEPolicyPriority")
              (may :GlueCEPolicyMaxRunningJobs "GlueCEPolicyMaxRunningJobs")
              (may :GlueCEPolicyMaxTotalJobs "GlueCEPolicyMaxTotalJobs")
              (may :GlueCEPolicyMaxCPUTime "GlueCEPolicyMaxCPUTime")
              (may :GlueCEPolicyMaxWallClockTime "GlueCEPolicyMaxWallClockTime")
              (may :GlueCEPolicyAssignedJobSlots "GlueCEPolicyAssignedJobSlots")
              (may :GlueCEPolicyMaxObtainableWallClockTime "GlueCEPolicyMaxObtainableWallClockTime")
              (may :GlueCEPolicyMaxObtainableCPUTime "GlueCEPolicyMaxObtainableCPUTime")
              (may :GlueCEPolicyMaxWaitingJobs "GlueCEPolicyMaxWaitingJobs")
              (may :GlueCEPolicyMaxSlotsPerJob "GlueCEPolicyMaxSlotsPerJob")
              (may :GlueCEPolicyPreemption "GlueCEPolicyPreemption")
              (may :GlueCEAccessControlBaseRule "GlueCEAccessControlBaseRule")
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueHostMainMemory "GlueHostMainMemory"
              (superclass :GlueClusterTop)
              (may :GlueHostMainMemoryRAMSize "GlueHostMainMemoryRAMSize")
              (may :GlueHostMainMemoryRAMAvailable "GlueHostMainMemoryRAMAvailable")
              (may :GlueHostMainMemoryVirtualSize "GlueHostMainMemoryVirtualSize")
              (may :GlueHostMainMemoryVirtualAvailable "GlueHostMainMemoryVirtualAvailable"))

(object-class :labeledURIObject "labeledURIObject"
              (superclass :top)
              (may :labeledURI "labeledURI"))

(object-class :GlueCESEBindGroup "GlueCESEBindGroup"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueCESEBindGroupCEUniqueID "GlueCESEBindGroupCEUniqueID")
              (may :GlueCESEBindGroupSEUniqueID "GlueCESEBindGroupSEUniqueID"))

(object-class :GlueHostFile "GlueHostFile"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostFileName "GlueHostFileName")
              (may :GlueHostFileSize "GlueHostFileSize")
              (may :GlueHostFileCreationDate "GlueHostFileCreationDate")
              (may :GlueHostFileLastModified "GlueHostFileLastModified")
              (may :GlueHostFileLastAccessed "GlueHostFileLastAccessed")
              (may :GlueHostFileLatency "GlueHostFileLatency")
              (may :GlueHostFileLifeTime "GlueHostFileLifeTime")
              (may :GlueHostFileOwner "GlueHostFileOwner"))

(object-class :GlueHostLocalFileSystem "GlueHostLocalFileSystem"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostLocalFileSystemName "GlueHostLocalFileSystemName")
              (may :GlueHostLocalFileSystemRoot "GlueHostLocalFileSystemRoot")
              (may :GlueHostLocalFileSystemSize "GlueHostLocalFileSystemSize")
              (may :GlueHostLocalFileSystemAvailableSpace "GlueHostLocalFileSystemAvailableSpace")
              (may :GlueHostLocalFileSystemReadOnly "GlueHostLocalFileSystemReadOnly")
              (may :GlueHostLocalFileSystemType "GlueHostLocalFileSystemType")
              (may :GlueHostLocalFileSystemClient "GlueHostLocalFileSystemClient"))

(object-class :pkiUser "pkiUser"
              (superclass :top)
              (may :userCertificate "userCertificate"))

(object-class :residentialPerson "residentialPerson"
              (superclass :person)
              (structural)
              (must :l "l")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l"))

(object-class :strongAuthenticationUser "strongAuthenticationUser"
              (superclass :top)
              (must :userCertificate "userCertificate"))

(object-class :GlueCEState "GlueCEState"
              (superclass :GlueCETop)
              (may :GlueCEStateRunningJobs "GlueCEStateRunningJobs")
              (may :GlueCEStateWaitingJobs "GlueCEStateWaitingJobs")
              (may :GlueCEStateTotalJobs "GlueCEStateTotalJobs")
              (may :GlueCEStateStatus "GlueCEStateStatus")
              (may :GlueCEStateWorstResponseTime "GlueCEStateWorstResponseTime")
              (may :GlueCEStateEstimatedResponseTime "GlueCEStateEstimatedResponseTime")
              (may :GlueCEStateFreeJobSlots "GlueCEStateFreeJobSlots"))

(object-class :extensibleObject "extensibleObject"
              (superclass :top))

(object-class :GlueHostApplicationSoftware "GlueHostApplicationSoftware"
              (superclass :GlueClusterTop)
              (may :GlueHostApplicationSoftwareRunTimeEnvironment "GlueHostApplicationSoftwareRunTimeEnvironment"))

(object-class :olcFrontendConfig "olcFrontendConfig"
              (may :olcDefaultSearchBase "olcDefaultSearchBase")
              (may :olcPasswordHash "olcPasswordHash")
              (may :olcSortVals "olcSortVals"))

(object-class :pilotDSA "pilotDSA"
              (superclass :dsa)
              (structural)
              (may :dSAQuality "dSAQuality"))

(object-class :room "room"
              (superclass :top)
              (structural)
              (may :roomNumber "roomNumber")
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :telephoneNumber "telephoneNumber"))

(object-class :dmd "dmd"
              (superclass :top)
              (structural)
              (must :dmdName "dmdName")
              (may :userPassword "userPassword")
              (may :searchGuide "searchGuide")
              (may :seeAlso "seeAlso")
              (may :businessCategory "businessCategory")
              (may :x121Address "x121Address")
              (may :registeredAddress "registeredAddress")
              (may :destinationIndicator "destinationIndicator")
              (may :preferredDeliveryMethod "preferredDeliveryMethod")
              (may :telexNumber "telexNumber")
              (may :teletexTerminalIdentifier "teletexTerminalIdentifier")
              (may :telephoneNumber "telephoneNumber")
              (may :internationaliSDNNumber "internationaliSDNNumber")
              (may :facsimileTelephoneNumber "facsimileTelephoneNumber")
              (may :street "street")
              (may :postOfficeBox "postOfficeBox")
              (may :postalCode "postalCode")
              (may :postalAddress "postalAddress")
              (may :physicalDeliveryOfficeName "physicalDeliveryOfficeName")
              (may :st "st")
              (may :l "l")
              (may :description "description"))

(object-class :document "document"
              (superclass :top)
              (structural)
              (must :documentIdentifier "documentIdentifier")
              (may :description "description")
              (may :seeAlso "seeAlso")
              (may :documentTitle "documentTitle")
              (may :documentVersion "documentVersion")
              (may :documentAuthor "documentAuthor")
              (may :documentLocation "documentLocation")
              (may :documentPublisher "documentPublisher"))

(object-class :GlueHostProcessorLoad "GlueHostProcessorLoad"
              (superclass :GlueClusterTop)
              (may :GlueHostProcessorLoadLast1Min "GlueHostProcessorLoadLast1Min")
              (may :GlueHostProcessorLoadLast5Min "GlueHostProcessorLoadLast5Min")
              (may :GlueHostProcessorLoadLast15Min "GlueHostProcessorLoadLast15Min"))

(object-class :olcBdbConfig "olcBdbConfig"
              (superclass :olcDatabaseConfig)
              (structural)
              (must :olcDbDirectory "olcDbDirectory")
              (may :olcDbCacheSize "olcDbCacheSize")
              (may :olcDbCheckpoint "olcDbCheckpoint")
              (may :olcDbConfig "olcDbConfig")
              (may :olcDbCryptFile "olcDbCryptFile")
              (may :olcDbCryptKey "olcDbCryptKey")
              (may :olcDbNoSync "olcDbNoSync")
              (may :olcDbDirtyRead "olcDbDirtyRead")
              (may :olcDbIDLcacheSize "olcDbIDLcacheSize")
              (may :olcDbIndex "olcDbIndex")
              (may :olcDbLinearIndex "olcDbLinearIndex")
              (may :olcDbLockDetect "olcDbLockDetect")
              (may :olcDbMode "olcDbMode")
              (may :olcDbSearchStack "olcDbSearchStack")
              (may :olcDbShmKey "olcDbShmKey")
              (may :olcDbCacheFree "olcDbCacheFree")
              (may :olcDbDNcacheSize "olcDbDNcacheSize")
              (may :olcDbPageSize "olcDbPageSize"))

(object-class :Mds "Mds"
              (structural)
              (may :Mds-validfrom "Mds-validfrom")
              (may :Mds-validto "Mds-validto")
              (may :Mds-keepto "Mds-keepto")
              (may :Mds-Vo-name "Mds-Vo-name"))

(object-class :GlueVOInfo "GlueVOInfo"
              (superclass :GlueSATop)
              (structural)
              (must :GlueVOInfoLocalID "GlueVOInfoLocalID")
              (may :GlueVOInfoName "GlueVOInfoName")
              (may :GlueVOInfoPath "GlueVOInfoPath")
              (may :GlueVOInfoTag "GlueVOInfoTag")
              (may :GlueVOInfoAccessControlBaseRule "GlueVOInfoAccessControlBaseRule"))

(object-class :GlueSoftware "GlueSoftware"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueSoftwareLocalID "GlueSoftwareLocalID")
              (may :GlueSoftwareName "GlueSoftwareName")
              (may :GlueSoftwareVersion "GlueSoftwareVersion")
              (may :GlueSoftwareInstalledRoot "GlueSoftwareInstalledRoot")
              (may :GlueSoftwareEnvironmentSetup "GlueSoftwareEnvironmentSetup")
              (may :GlueSoftwareModuleName "GlueSoftwareModuleName"))

(object-class :GlueSite "GlueSite"
              (superclass :GlueGeneralTop)
              (structural)
              (must :GlueSiteUniqueID "GlueSiteUniqueID")
              (may :GlueSiteDescription "GlueSiteDescription")
              (may :GlueSiteName "GlueSiteName")
              (may :GlueSiteUserSupportContact "GlueSiteUserSupportContact")
              (may :GlueSiteSysAdminContact "GlueSiteSysAdminContact")
              (may :GlueSiteSecurityContact "GlueSiteSecurityContact")
              (may :GlueSiteLocation "GlueSiteLocation")
              (may :GlueSiteLatitude "GlueSiteLatitude")
              (may :GlueSiteLongitude "GlueSiteLongitude")
              (may :GlueSiteWeb "GlueSiteWeb")
              (may :GlueSiteSponsor "GlueSiteSponsor")
              (may :GlueSiteOtherInfo "GlueSiteOtherInfo")
              (may :GlueSiteEmailContact "GlueSiteEmailContact")
              (may :GlueSchemaVersionMajor "GlueSchemaVersionMajor")
              (may :GlueSchemaVersionMinor "GlueSchemaVersionMinor"))

(object-class :GlueHost "GlueHost"
              (superclass :GlueClusterTop)
              (structural)
              (must :GlueHostUniqueID "GlueHostUniqueID")
              (may :GlueHostName "GlueHostName"))

(object-class :olcLdifConfig "olcLdifConfig"
              (superclass :olcDatabaseConfig)
              (structural)
              (must :olcDbDirectory "olcDbDirectory"))

(object-class :referral "referral"
              (superclass :top)
              (structural)
              (must :ref "ref"))

(object-class :GlueHostNetworkAdapter "GlueHostNetworkAdapter"
              (superclass :GlueClusterTop)
              (may :GlueHostNetworkAdapterOutboundIP "GlueHostNetworkAdapterOutboundIP")
              (may :GlueHostNetworkAdapterInboundIP "GlueHostNetworkAdapterInboundIP")
              (may :GlueHostNetworkAdapterName "GlueHostNetworkAdapterName")
              (may :GlueHostNetworkAdapterIPAddress "GlueHostNetworkAdapterIPAddress")
              (may :GlueHostNetworkAdapterMTU "GlueHostNetworkAdapterMTU"))

(object-class :olcIncludeFile "olcIncludeFile"
              (superclass :olcConfig)
              (structural)
              (must :olcInclude "olcInclude")
              (may :cn "cn")
              (may :olcRootDSE "olcRootDSE"))

(object-class :dynamicObject "dynamicObject"
              (superclass :top))

(object-class :GlueCETop "GlueCETop"
              (superclass :GlueTop))

(object-class :dcObject "dcObject"
              (superclass :top)
              (must :dc "dc"))

(object-class :GlueInformationService "GlueInformationService"
              (superclass :GlueGeneralTop)
              (may :GlueInformationServiceURL "GlueInformationServiceURL"))

(object-class :GlueSLDirectory "GlueSLDirectory"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLDirectoryName "GlueSLDirectoryName")
              (may :GlueSLDirectorySize "GlueSLDirectorySize")
              (may :GlueSLDirectoryCreationDate "GlueSLDirectoryCreationDate")
              (may :GlueSLDirectoryLastModified "GlueSLDirectoryLastModified")
              (may :GlueSLDirectoryLastAccessed "GlueSLDirectoryLastAccessed")
              (may :GlueSLDirectoryLatency "GlueSLDirectoryLatency")
              (may :GlueSLDirectoryLifeTime "GlueSLDirectoryLifeTime")
              (may :GlueSLDirectoryPath "GlueSLDirectoryPath"))

(object-class :applicationProcess "applicationProcess"
              (superclass :top)
              (structural)
              (must :cn "cn")
              (may :seeAlso "seeAlso")
              (may :ou "ou")
              (may :l "l")
              (may :description "description"))

(object-class :GlueHostSMPLoad "GlueHostSMPLoad"
              (superclass :GlueClusterTop)
              (may :GlueHostSMPLoadLast1Min "GlueHostSMPLoadLast1Min")
              (may :GlueHostSMPLoadLast5Min "GlueHostSMPLoadLast5Min")
              (may :GlueHostSMPLoadLast15Min "GlueHostSMPLoadLast15Min"))

(object-class :GlueSLRemoteFileSystem "GlueSLRemoteFileSystem"
              (superclass :GlueSLTop)
              (structural)
              (must :GlueSLRemoteFileSystemName "GlueSLRemoteFileSystemName")
              (may :GlueSLRemoteFileSystemRoot "GlueSLRemoteFileSystemRoot")
              (may :GlueSLRemoteFileSystemSize "GlueSLRemoteFileSystemSize")
              (may :GlueSLRemoteFileSystemAvailableSpace "GlueSLRemoteFileSystemAvailableSpace")
              (may :GlueSLRemoteFileSystemReadOnly "GlueSLRemoteFileSystemReadOnly")
              (may :GlueSLRemoteFileSystemType "GlueSLRemoteFileSystemType")
              (may :GlueSLRemoteFileSystemName "GlueSLRemoteFileSystemName")
              (may :GlueSLRemoteFileSystemServer "GlueSLRemoteFileSystemServer"))