(for-each :GlueSite
  (add-instance :GlueSite
    (mapping :GlueSiteUniqueID :GlueSiteUniqueID)
    (mapping :GlueSiteName :GlueSiteName)
    (mapping :GlueSiteDescription :GlueSiteDescription)
    (mapping :GlueSiteEmailContact :GlueSiteEmailContact)
    (mapping :GlueSiteSysAdminContact :GlueSiteSysAdminContact)
    (mapping :GlueSiteUserSupportContact :GlueSiteUserSupportContact)
    (mapping :GlueSiteSecurityContact :GlueSiteSecurityContact)
    (mapping :GlueSiteLocation :GlueSiteLocation)
    (mapping :GlueSiteLatitude :GlueSiteLatitude)
    (mapping :GlueSiteLongitude :GlueSiteLongitude)
    (mapping :GlueSiteWeb :GlueSiteWeb)
    (mapping :GlueSiteSponsor :GlueSiteSponsor)
    (mapping :GlueSiteOtherInfo :GlueSiteOtherInfo)))
